### ISSUE TITLE
How to remove the desktopHCP module?

### ISSUE THREAD

**Issue by sferoze** [wojtkowiak/meteor-desktop#101]
In .desktop/settings.json, if I set `"desktopHCP":  false,` it complains that I need to remove the desktopHCP module and does not build. 

How do I remove the desktopHCP module? Where is it?

**Comment by wojtkowiak** [comment]
This should not happen - I mean you should not have any problem with building.
Can you paste the message you are getting?

**Comment by wojtkowiak** [comment]
Oh wait, you mean that building with `-b` fails?
If so do
```
meteor remove omega:meteor-desktop-watcher omega:meteor-desktop-bundler
```
This will be handled automatically in 1.0

**Comment by wojtkowiak** [comment]
This was released quite some time ago.
