### ISSUE TITLE
Small deprecations

### ISSUE THREAD

**Issue by fabien-h** [wojtkowiak/meteor-desktop#104]
'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
    'webkitIndexedDB' is deprecated. Please use 'indexedDB' instead.

Not really a bug yet.

**Comment by wojtkowiak** [comment]
When do you see those? In desktop app console? Can you also see this in a clean meteor project with meteor-desktop?

**Comment by KoenLav** [comment]
I also see these when running a Meteor 1.5 project, have not tried with a clean project.

**Comment by wojtkowiak** [comment]
Ok, I did not arrive in 1.5 land yet :) Will check where is this coming from.

**Comment by KoenLav** [comment]
This is resolved, suggest closing this issue.
