### ISSUE TITLE
HCP not working when serving through nginx / Cloudflare

### ISSUE THREAD

**Issue by KoenLav** [wojtkowiak/meteor-desktop#107]
"[autoupdate] download failure: failed at verifyResponse: Cannot read property 'match' of undefined"

Any pointers?

**Comment by KoenLav** [comment]
Seems to come from: const matches = eTag.match(this.eTagWithSha1HashPattern);

**Comment by wojtkowiak** [comment]
Hey,

do you have your server exposed over some kind of proxy like i.e. nginx?

**Comment by KoenLav** [comment]
Yes, we use meteor up with Nginx and Docker.

Op 10 jun. 2017 10:26 a.m. schreef "Bartosz Wojtkowiak" <
notifications@github.com>:

**Comment by KoenLav** [comment]
Just to clarify further: we're also proxying traffic through Cloudflare.

User -> Cloudflare -> Nginx -> Meteor (Docker container)

Trying out your fix right now.

**Comment by KoenLav** [comment]
I commented on the commit; should be === instead of !==.

When changed it's working fine again!

**Comment by wojtkowiak** [comment]
> I commented on the commit; should be === instead of !==.

Yep, been thinking about one thing and wrote the other ;)

v0.7.2 with this fix is released, let me know if this can be closed.
And thanks for you time investigating this!

**Comment by KoenLav** [comment]
Working just fine now!
