### ISSUE TITLE
Experimental localStorage not working with UAC

### ISSUE THREAD

**Issue by KoenLav** [wojtkowiak/meteor-desktop#110]
When UAC is enabled (at the highest level) the experimental localStorage method (possibly also the default localStorage method) is not working.

That's fine, I guess, but I can't seem to find an error in the log anywhere?

**Comment by KoenLav** [comment]
Have you considered using this package for localstorage?

https://www.npmjs.com/package/electron-json-storage

**Comment by KoenLav** [comment]
I've created a Module for that package:

`/* eslint-disable no-unused-vars */
import moduleJson from './module.json';
import electronStorage from 'electron-json-storage';

/**
 * Example module.
 *
 * @param {Object} log         - Winston logger instance
 * @param {Object} skeletonApp - reference to the skeleton app instance
 * @param {Object} appSettings - settings.json contents
 * @param {Object} eventsBus   - event emitter for listening or emitting events
 *                               shared across skeleton app and every module/plugin
 * @param {Object} modules     - references to all loaded modules
 * @param {Object} settings    - module settings
 * @param {Object} Module      - reference to the Module class
 * @constructor
 */
export default class NodeSocket {
  constructor({ log, skeletonApp, appSettings, eventsBus, modules, settings, Module }) {
    /**
     * You can delete unused vars from the param destructuring.
     * Left them here just to emphasize what is passed. Delete the eslint rule at the top
     * when done.
     * You can also just have a one `config` param and do `Object.assign(this, config);`
     */
    this.module = new Module(moduleJson.name);

    // Get the automatically predefined logger instance.
    this.log = log;
    this.eventsBus = eventsBus;

    // Never do time consuming or blocking things directly in the constructor.
    // Instead hook to 'beforeDesktopJsLoad`, `desktopLoaded` or `afterInitialization` events.
    // This will also ensure plugins providing things like splash screens will be able
    // to start as quickly as possible.
    this.eventsBus.on('desktopLoaded', () => {
      this.init();
    });
  }

  init() {
    // Do some initialization if necessary.
    this.registerApi();

    // Lets inform that the module has finished loading.
    this.eventsBus.emit(`${moduleJson.name}.loaded`);
  }

  // Usage
  // Desktop.fetch(moduleName, eventName, timeout, ...args).then().catch();
  // Desktop.fetch('JSONStorage', 'getAll').then((data) => { console.log(data) }).catch(() => { console.log("FAIL"); });

  registerApi() {
    this.module.on('getAll', (event, fetchId) => {
      electronStorage.get('clientSettings', (error, value) => {
        if (error) {
          this.module.respond('getAll', fetchId, error);
        }
        else {
          this.module.respond('getAll', fetchId, value);
        }
      });
    });

    this.module.on('setItem', (event, fetchId, key, value) => {
      electronStorage.set(key, value, (error) => {
        this.module.respond('setItem', fetchId, error);
      });
    });
  }
}
`

**Comment by KoenLav** [comment]
@wojtkowiak if you want I can extend try to extend this module to become a plugin (also replacing Meteor._localStorage)?

**Comment by matthova** [comment]
@KoenLav I'm up for testing whatever you implement on a barebones todo-list app on windows, mac, and linux.

**Comment by KoenLav** [comment]
@matthova I decided to use another implementation based on electron-settings (it seems to be better for the useCase of storing device settings (which is what we are using this for).

https://pastebin.com/cqVsZiqq

Usage instructions in the comments above the methods.

@wojtkowiak is there an easier way to expose these functionalities from the main process to the webview? Or is using Desktop.fetch the most simple way imaginable.

**Comment by wojtkowiak** [comment]
Hey, sorry for not responding. I had a slight offline period recently ;)

> @wojtkowiak is there an easier way to expose these functionalities from the main process to the webview? Or is using Desktop.fetch the most simple way imaginable.

Yes, the `Desktop.fetch` intent is to ease it out. Probably there is still room to make the IPC more dev friendly by automating declaration of `Desktop.on` and a few other things but that is not on my radar right now.

I am interested in why it fails. It probably do not have rights to modify the files. I will check it out as I need to know that for the final mechanism for LocalStorage and IndexedDB that will come soon in the next major release.

**Comment by KoenLav** [comment]
No problem!

Is there a specific reason why you are not making use of one of the already existing packages like Electron JSON Storage or Electron Settings?

**Comment by KoenLav** [comment]
@wojtkowiak we decided to make use of Electron Settings for now.

It seems to work consistently.

For consistency I think we would prefer migrating to LocalStorage/IndexedDB (to use the same methods platform independently), however for iOS we're also making use of a separate storage driver for localforage (cordovaSQLiteDriver).
