### ISSUE TITLE
TAPi18n & CFS: HTTP calls to server blocked by CORS

### ISSUE THREAD

**Issue by dorandeluz** [wojtkowiak/meteor-desktop#114]
Hi wojtkowiak,

First of all, thanks for the awesome framework. We'll gladly contribute once our app generates revenue.

As a heads up to others, we had issues with packages that need to make custom http calls to the meteor server to work, namely tapi18n and cfs.

The first part of the fix is simply to add Meteor.isDesktop where Meteor.isCordova appears, which prepends Meteor.absoluteUrl() to the server resources' paths. However that would not be enough as we'd then get e.g.
`XMLHttpRequest cannot load http://127.0.0.1:3000/cfs/servertime. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:8062' is therefore not allowed access.`

The reason is that there's a rule for "http://localhost" in https://github.com/CollectionFS/Meteor-http-methods's http.methods.server.api.js's setCordovaHeaders, but not for "http://127.0.0.1" which is used by the Desktop client. Patching these rules to add that address makes these 2 packages work again. 

On a side note, there's a comment in that function saying "Match http://localhost:port for Cordova clients in Meteor 1.3". Assuming that this is true in general (??), ie. that Cordova clients always use localhost and not 127.0.0.1, maybe you could consider changing Desktop clients' root url to localhost too if possible, so that this problem doesn't appear with other packages.

**Comment by wojtkowiak** [comment]
Hey @dorandeluz ,

thanks for letting me know. If you'd like, I can add a link to your product in readme, once it's released.

With tap18n maybe it would be worthy to make a pull request for that. After I release 1.0 I will try to make this integration more official so it would be easier to convince others to support `meteor-desktop` in their packages.

About `localhost` in general, it is safer to use `127.0.0.1` as `localhost` might be overridden, point to ipv6 or not be present at all. Of course those are edge cases, but still I'd rather use the IP. But if you'd like I can add a swith to settings.json that would change the url to localhost - so let me know.

**Comment by dorandeluz** [comment]
Yes a pull request on their end would make sense. Let's see after 1.0.

About `localhost` maybe it's worth keeping the problem in mind in case it reappears with other packages. But if it's only these two packages and they accept the pull request, I don't think you need to change anything at this point.

Thanks
