### ISSUE TITLE
Native modules with 32-bit

### ISSUE THREAD

**Issue by crippledjosh** [wojtkowiak/meteor-desktop#116]
Hi, sorry if there is already a way to do this, but I cannot find it. I've got native modules and i need to build a 32-bit version of the app on a 64-bit machine. Now I've done all the easy things like running the packager with --ia32 which makes the app 32-bit but it still seems to pull the 64-bit versions of the native modules from npm. I've even found that bit of the code that looks like it should handle this in electronBuilder, where it checks to see if the modules need rebuilding because of an arch change.
`const rebuild = platformMatches && context.arch !== this.lastRebuild.arch;`
 but I cannot seem to set the context arch to 32-bit. 

I even get this mixture of saying 32-bit and 64-bit in the logs

> DEBUG  electronBuilder:  calling installOrRebuild from electron-builder for arch x64
> Rebuilding native production dependencies for win32:x64
> ...
> Parameter format not correct -
> ...
> INFO  electron-packager:  packaging 'Capitalise' for platform 'win32-ia32' using electron v1.4.16

I left the "Parameter format not correct -" because I'm not sure if it's relevant or not. 

Is there somewhere else that I need to set it as 32-bit seems slightly odd that I would have to but I'm very willing to if thats the case.

**Comment by crippledjosh** [comment]
Just after writing this I think I have found at least some offending code. 

`return this.$.electronBuilder.installOrRebuild('x64');`

To me this looks hardwired to build all modules at 64-bit

**Comment by wojtkowiak** [comment]
Hey,

when using `build-installer` it should work - I am building 32 bit versions of my project with binary deps and it works correctly.
When using `package` indeed the line you have found is not correct - this will be fixed within 2 days.

**Comment by crippledjosh** [comment]
Ahh excellent, yes i only use package. When i tried using the installer it gave me some error that I couldn't figure out, also I quite like having a full tool like inno to build the actual installer from the exe file. Thanks for getting back to me on this.

**Comment by crippledjosh** [comment]
Tried it yesterday btw it worked perfectly. Thanks.

**Comment by wojtkowiak** [comment]
Forgot to notify you. You've used the `0.8.1`?

**Comment by crippledjosh** [comment]
Yeah no worries I checked and saw that there was a new version and gave it a go. Yes I've used it created a 32-bit version and everything seems to work now, should have users using it soon, so that will be the first test actually on a 32-bit machine so will know more then.

**Comment by wojtkowiak** [comment]
Great 👍 
Sorry you had to wait a few days for that.

**Comment by crippledjosh** [comment]
Ahh no worries i was on holiday and you timed the fix perfectly for me so I had no pressure to work whilst i was meant to be relaxing.

**Comment by wojtkowiak** [comment]
Can this be closed?

**Comment by crippledjosh** [comment]
Yes absolutely, i've had live copies of both architectures out there for a 9 months now :).

**Comment by wojtkowiak** [comment]
Great :)
