### ISSUE TITLE
[ ] Remember Me?

### ISSUE THREAD

**Issue by AndyNormore** [wojtkowiak/meteor-desktop#118]
Hi all, excellent plugin. Thank you.

However, my web app has a "Remember Me" setting.

The desktop version does not. How can this be fixed?

**Comment by wojtkowiak** [comment]
Hey, 
not exactly sure what do you mean?
What are you using for accounts and login screen?
If it is just about remember me not respected on meteor-desktop than its an issue with localstorage. What version of meteor-desktop are you using?

**Comment by AndyNormore** [comment]
Thanks for the reply, here's some screen shots:

DESKTOP:

![image](https://user-images.githubusercontent.com/1661561/29461826-24db4c64-83fb-11e7-954f-31f196618335.png)


..............................

Shoot, well, look at that, it's not there on the web app either. I guess this has nothing to do with your plugin, and likely something on my server! DOH!

Well, thanks for your reply anyway.
