### ISSUE TITLE
How to access Browser Window

### ISSUE THREAD

**Issue by sakujo** [wojtkowiak/meteor-desktop#124]
Hello.

Could you tell me where you are creating the BrowserWindow?
Is there any way to access the BrowserWindow on Meteor side?

I wanna access the BrowserWindow to check if it's focused/minimzed etc.

The eventBus doesn't provide a method like isMinimzed(). That's why i thought, that
i could access the Browser window via remote and accessing BrowserWindow

I'm doing the following:
const remote = window.require('electron').remote;

getting the error:
Uncaught Error: Cannot find module 'electron'.

p.s. Im running the project with npm run desktop and i can't access the assets folder
with'\___desktop\meteor.png'

Any ideas?

**Comment by KoenLav** [comment]
You should probably look into building a bridge between Meteor code and Electron code using IPC.

        eventsBus.on('windowCreated', (window) => {
            mainWindow = window;

            // Uncomment to show the devTools even in production (for debugging production only issues)
            // window.webContents.openDevTools()

            window.webContents.on('crashed', Desktop.windowCrashedHandler);

            window.on('unresponsive', Desktop.windowUnresponsiveHandler);

            // Launch the app in fullscreen
            window.webContents.on('dom-ready', () => {
                window.setFullScreen(true);
            });

            // Listen for the minimize event
            desktop.on('minimize', () => {
                window.minimize();
            });
        });

**Comment by lacymorrow** [comment]
@KoenLav How do I emit an event from the Meteor side/renderer process to be executed by desktop.js?

**Comment by KoenLav** [comment]
Desktop.send('desktop', 'minimize');
