### ISSUE TITLE
Submitting to Mac App Store Application Loader Error - No version found for 'adamId - platform' (XXXXXXXXXX-iOS App). 

### ISSUE THREAD

**Issue by sferoze** [wojtkowiak/meteor-desktop#127]
I am trying to submit my electron app to the mac app store

I generated the Mac Distribution Certification, and also created an entry in iTunes Connect for the Mac App.

I edited the Info.plist to include correct Bundle ID. (com.myapp.myapp-mac)

Whenever I have waited 24 hours since adding the record and now when I try and upload, I get the error

No version found for 'adamId - platform' (XXXXXXXXXX-iOS App).  If this problem persists for more than 24 hours, please contact your Apple representative.

**Comment by sferoze** [comment]
@wojtkowiak have you submitted your meteor-desktop app to the app store?

**Comment by sferoze** [comment]
This guide here helped me:

https://github.com/electron/electron/blob/master/docs/tutorial/mac-app-store-submission-guide.md

In addition, I had to download and use Application Loader 3.1. Version 3.7 did not work for me, kept getting `No version found for 'adamId - platform' (XXXXXXXXXX-iOS App)`

But with application loader 3.1 it worked, after following the electron submission guide. 

You have to package the .app into a .pkg using the guide

**Comment by wojtkowiak** [comment]
If you'd like to make a quick manual for that I would be more than happy to link/include it somewhere in the docs!
I did not yet published any of my projects to app store unfortunately. Also if you'd like to have some free advertising I can make a link to your app in the docs.
