### ISSUE TITLE
devTools needed but is disabled by default

### ISSUE THREAD

**Issue by nzomedia** [wojtkowiak/meteor-desktop#129]
Hello,

Thank you for making meteor-desktop. I'm currently trying to add a feature to my app: basically i want to change the URL used to connect to the Meteor server application after installation.
I'm facing some problems, but my main consern is that i can't open devTools, i use a linux target machine and Ctrl+shift+i doesn't work. I see in `settings.json` that devTools is true, but when i try to make a package using:
```
npm run desktop -- package http://localhost:3000
```
Among the printed lines i see: 
```
METEOR-DESKTOP v0.10.0

package/build-installer implies setting --production, setting it for you
REMINDER: your Meteor project should be running now on port 3000
```
And in the documentation it's said that in production, devTools'setting is automatically put to false.

So, am i missing something?

**Comment by KoenLav** [comment]
In desktop.js try:

window.webContents.openDevTools();

**Comment by nzomedia** [comment]
Thank you @KoenLav i tested your instruction inside the callback function of windowCreated event and it works. devTools works.
I'm sorry i didn't see your reply sooner.
