### ISSUE TITLE
Meteor 1.6: release gets overwritten in castMeteorReleaseToSemver

### ISSUE THREAD

**Issue by KoenLav** [wojtkowiak/meteor-desktop#131]
In this function:

return (this.getMeteorRelease() + '.0.0').match(/(^\d+\.\d+\.\d+)/gmi)[0];

'.0.0' seems to overwrite '1.6', causing the build to fail with a:

TypeError: Cannot read property '0' of null

Which is very strange; I tried:

var release = this.getMeteorRelease();

console.log(release); // Outputs '1.6' (string)

release += '.0.0';

console.log(release); // Outputs '.0.0' (string)

**Comment by FrancisBou** [comment]
I have this same error under windows only. This [comment](https://github.com/wojtkowiak/meteor-desktop/issues/103#issuecomment-332201545) is my quickfix for now.

**Comment by KoenLav** [comment]
Created a PR for this bug: https://github.com/wojtkowiak/meteor-desktop/pull/135
