### ISSUE TITLE
Local Filesystem URLs don't support whitespace

### ISSUE THREAD

**Issue by met5678** [wojtkowiak/meteor-desktop#133]
I've got an app that needs to store some assets in a cache. I was hoping to use the `appData` or `userData` directories to do this, but on OSX the URLs given by `Desktop.getFileUrl` don't work. For example:

Actual Path: `/Users/andrew/Library/Application Support/clips/test.mp4`
`Desktop.getFileUrl` result: `/local-filesystem//Users/andrew/Library/Application Support/clips/test.mp4`
Resolved URL in Chrome: `http://localhost:3002/local-filesystem//Users/andrew/Library/Application%20Support/clips/test.mp4`

For a path that doesn't have whitespaces in it, everything works fine. But since the default `appData` directory on OSX is called `Application Support`, this precludes use of this directory.

**Comment by wojtkowiak** [comment]
Sorry for the delay, just published 0.11.2 with this.

**Comment by wojtkowiak** [comment]
can this be closed?

**Comment by andrew-luminal** [comment]
Absolutely, yes, thank you!

**Comment by met5678** [comment]
Yes, thank you for merging it in!
