### ISSUE TITLE
builds on High Sierra are failing

### ISSUE THREAD

**Issue by wvanooijen92** [wojtkowiak/meteor-desktop#138]
Electron hangs on step "Building DMG".

Seems to be [this](https://github.com/electron-userland/electron-builder/issues/2115) issue.

Do you accept PRs?

**Comment by xcv58** [comment]
I have the same issue, any update?

**Comment by wvanooijen92** [comment]
Not from my part, I am also still waiting on it. I have tried to update `electron-builder` myself, but I couldn't get it to work:(

**Comment by Jaradacl** [comment]
+1

**Comment by Ajaay** [comment]
+1

**Comment by Ajaay** [comment]
How is everyone working around this issue at the moment? Haven't been able to find a way of downgrading back to Sierra so stuck without the ability to release new builds at the moment

**Comment by wvanooijen92** [comment]
I am running a build server on a old mac book temporarily, we are still hoping this issue gets fixed. You could take a look at CircleCI they recently released an OSX build service. I did not have time to take a look at it though

**Comment by wojtkowiak** [comment]
Hey, sorry it took so long, still struggling to get any free time to commit to this project.
Just released `0.12.0` with `electron-builder` update, please check it out.

**Comment by wojtkowiak** [comment]
Is this working now for you guys?

**Comment by wvanooijen92** [comment]
@wojtkowiak Sorry for my late response. I can build again, thank you for taking a look!
