### ISSUE TITLE
Generate a windows exe/installer on Linux

### ISSUE THREAD

**Issue by Rongky** [wojtkowiak/meteor-desktop#14]
With this package, is it possible to generate/build a windows exe or installer on Linux? 
I'm on ubuntu 16.04 and meteor 1.4.2.1. 

Thanks for this package!!!

**Comment by wojtkowiak** [comment]
Yes and no :wink:
Check here for the requirements: https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build#to-build-app-for-windows-on-linux

Currently the `build-installer` is only building for current platform, but I will add a possibility to override this.
This should be released in `0.2.0` within few days. Currently the plan is to release this on Monday.

**Comment by Rongky** [comment]
This would be great!!
Looking forward to version 0.2.0 then.

Thanks @wojtkowiak .

**Comment by Rongky** [comment]
This is to confirm that I have successfully created a windows installer from linux with **NO HASSLE, NO ISSUES & NO ADDITIONAL CODE.**  That also goes with linux package builder/installer. 

Finally, meteor-desktop has arrived and I hope it will be part of the core or at least, be given its own rightful place in the official meteor guide. Thanks @wojtkowiak for this awesome package.

**Comment by lacymorrow** [comment]
@wojtkowiak this is the best packager for Meteor-Electron projects hands-down. I'm able to package for *Windows, Linux, and macOS from any environment*!
