### ISSUE TITLE
Error when creating/building installer for linux (ubuntu 16.04)

### ISSUE THREAD

**Issue by Rongky** [wojtkowiak/meteor-desktop#15]
When running npm run desktop -- build-installer [ddp_url], below is the error:

...
Packaging for platform linux x64 using electron 1.4.4 to .desktop-installer/linux-unpacked

Unhandled rejection Error: Exit code: ENOENT. spawn icns2png ENOENT
    at /home/user/myMeteorApp/node_modules/electron-builder/src/util/util.ts:102:16
    at exithandler (child_process.js:220:5)
    at ChildProcess.errorhandler (child_process.js:232:5)
    at emitOne (events.js:77:13)
    at ChildProcess.emit (events.js:169:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
From previous event:
   ...
ERROR  installerBuilder:  error while building installer:  [Error: Exit code: ENOENT. spawn icns2png ENOENT]

However, its fine when only packaging for linux (npm run desktop -- package [ddp_url]).

**Comment by aboire** [comment]
sudo apt-get install icnsutils

**Comment by wojtkowiak** [comment]
You have to add `linux` property in `builderOptions` in `settings.json` and conform to these requirements https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build#linux.
I am interested if somebody could prepare a default `linux` config for the default `settings.json` in current scaffold as this is absent currently.

**Comment by wojtkowiak** [comment]
I will add some notes about it in the docs.

**Comment by Rongky** [comment]
Thanks for the replies.

After following this link (https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build#linux), below is the error:

    ERROR  installerBuilder:  error while building installer:  [Error: Exit code: 1. Command failed: gm convert -size 96x96 /tmp/electron-builder-1107-15860e9a7dc-0/t-1107-1-electron-builder-linux.iconset/icon_256x256x32.png -resize 96x96 /tmp/electron-builder-1107-15860e9a7dc-0/t-1107-1-electron-builder-linux.iconset/icon_96x96x32.png
    gm convert: Unable to open file (/tmp/electron-builder-1107-15860e9a7dc-0/t-1107-1-electron-builder-linux.iconset/icon_256x256x32.png) [No such file or directory].
    gm convert: Unable to open file (/tmp/electron-builder-1107-15860e9a7dc-0/t-1107-1-electron-builder-linux.iconset/icon_256x256x32.png) [No such file or directory].]

As a workaround per discussion here: https://github.com/electron-userland/electron-builder/issues/239,
creating a build/icons folder at the app's root directory and placing inside the following images/icons found at https://github.com/develar/onshape-desktop-shell/tree/master/build/icons, addresses the issue. 

However, it would be much cleaner if build/icons folder is inside .desktop/assets directory since it is part of meteor-desktop build process in linux. But either way, it doesn't matter as long as it works!!! 

Very much grateful for this package!!! Thanks!

**Comment by wojtkowiak** [comment]
I'm glad you have managed to work it out.
Thanks for sharing that knowledge. I will think about it as I already had a `.desktop/build` directory in plan for `0.3.0` as it is not nice that currently you can not split your assets to the ones needed by build process and the ones needed by the desktop app itself.

**Comment by SantoshSrinivas79** [comment]
@Rongky I'm trying to create a testapp but running into all sorts of issues.

I did `meteor create testApp` first, then `meteor --mobile-server=127.0.0.1:3000` in one terminal .. it shows the below warning:

`I20161116-08:18:29.259(5.5)? [meteor-desktop] .desktop HCP will not work because either web.cordova architecture is missing or the bundler had troubles with creating desktop.asar. Be sure that you are running mobile target or with --mobile-server.`

`meteor run desktop` throws the following error:

`ERROR  meteorApp:  no mobile build found at /home/ghost/temp/testApp/.meteor/local/build/programs/web.cordova
ERROR  meteorApp:  are you sure you did run meteor with --mobile-server?`

Can you pls advise on the exact steps to following to create a test app on Ubuntu?

Thank you.

**Comment by SantoshSrinivas79** [comment]
@Rongky ... pls ignore ... I didn't realize that I need to add a platform even I didnt need one ... I ran `meteor add-platform ios` and it started fine. Sorry!

**Comment by Rongky** [comment]
No probs @SantoshSrinivas79. That was also my initial error. This step was commented out in the docs, that's why.
