### ISSUE TITLE
[Feature Request] Integrate the latest electron-builder

### ISSUE THREAD

**Issue by enuoCM** [wojtkowiak/meteor-desktop#150]
Hi, Thanks for your awesome project. But could you help to integrate the latest electron-builder, such as 20.5.1.
It has fixed so many bugs from 20.0.8. Thanks again.

**Comment by wojtkowiak** [comment]
No problem, just released `0.14.1` with updated electron-builder

**Comment by enuoCM** [comment]
@wojtkowiak  Thanks! electron-builder 20.6.1 is comming now. ^_^

**Comment by wojtkowiak** [comment]
20.8.2 is now in `0.15.0` :)
I'll try to update it more frequently. If needed you can always ping me with a new issue.
