### ISSUE TITLE
[npm package incompatibility] pm2 fails with meteor-desktop

### ISSUE THREAD

**Issue by unl0v3d** [wojtkowiak/meteor-desktop#155]
I used to do my bundles manually and came across this package. But when i use pm2 with it it fail and pm2 dont launch up.

in my server code i have:
```
import pm2 from 'pm2';

pm2.connect(false, function(err) { 
    if (err) {
    console.log(err);
    process.exit(2);
    }
});
```
above code normaly must launch up pm2 which is ok without meteor-desktop.

any body knows what the problem can be? PS. pm2 dependcy added to .desktop dep. list already

**Comment by wojtkowiak** [comment]
PM2 is now supported but only in noDaemon mode:
`pm2.connect(true`
