### ISSUE TITLE
How do I use new modules that come natively with Electron?

### ISSUE THREAD

**Issue by sferoze** [wojtkowiak/meteor-desktop#162]
In Electron 2.0 beta a new inAppPurchase module has been added, to allow developers to utilize apple subscriptions in their app. 

I have edited meteor desktop to use the new electron 2.0 beta and have verified it is working. 

But I have no idea how to access the new module. It is not showing up anywhere. 

How can I use it?

https://github.com/electron/electron/blob/master/docs/api/in-app-purchase.md

**Comment by wojtkowiak** [comment]
Hey,
I did not test meteor-desktop with electron 2.0 but simply
```
const { inAppPurchase } from 'electron'
```
in .desktop/desktop.js should work. Does it throws anything?

**Comment by wojtkowiak** [comment]
Have you checked it?

**Comment by sferoze** [comment]
@wojtkowiak Ah yah thanks! It works! Gahh, I wish I had tried that before. I don't know what I was thinking.
