### ISSUE TITLE
Configurable default timeout for `Desktop.fetch`?

### ISSUE THREAD

**Issue by met5678** [wojtkowiak/meteor-desktop#163]
`Desktop.fetch` has a default timeout of 2000 milliseconds. I'm running this on some unpredictably slow tiny computers, and lags can often be higher than that even for simple operations if I'm reading anything from the filesystem. I've been setting it to higher than 2000 for most of my calls, wondering if there's just a way to set a default? If you're open to this, I'd be happy to try looking into the code and make a PR for it.

Thanks for such an amazing package, I've been doing some very cool things with it!

**Comment by wojtkowiak** [comment]
That's a reasonable request 🙂 
I will add a `setDefaultFetchTimeout(timeout)`, also I am thinking to add and alias to `fetch` that would not require to pass an undefined if you want to use the default so sth like this:
```
fetch(module, event, timeout = defaultTimeout, ...args) // explicit timeout
call(module, event, ...args) // `fetch` alias using implicit default timeout
```

**Comment by wojtkowiak** [comment]
@met5678 ping 🙂

**Comment by andrew-luminal** [comment]
Thank you very much, will start using it today!!

**Comment by met5678** [comment]
Thank you very much, will start using it today!

**Comment by wojtkowiak** [comment]
This went in today with `1.1.0`
