### ISSUE TITLE
Decouple electron, electron-builder and electron-packager versions from this package

### ISSUE THREAD

**Issue by KoenLav** [wojtkowiak/meteor-desktop#166]
Suggestion: allow users to override the version of electron, electron-builder and electron-packager in their ./desktop/settings.json.

**Comment by wojtkowiak** [comment]
Hey,
I've been thinking about this, but not sure yet how to do this properly. I mean not sure whats the correct approach in this situation.
I can strip those from meteor-desktop dependencies and when meteor-desktop is run check if they are already added to the project (so it would respect the already installed ones). If not meteor-desktop would install the default ones adding them to package.json of the meteor project.
One thing is that I will always be supporting one major.minor version of electron, so probably I should display a warning if you are using an older or newer one. Also there should be a command that will update your deps to the latest supported ones. 
Any thoughts on that?

**Comment by KoenLav** [comment]
@wojtkowiak I think for now a minimal implementation would suffice; relying on the current installed dependencies and only installing the default versions in the parent project whenever they are not installed yet.

I don't think the first implementation of this feature would require any notifications about unsupported versions. Simply listing the supported versions on the Readme would suffice, I think.

**Comment by Ajaay** [comment]
Has there been any more thought around this? 

I've got a chrome issue that's introduced with newer versions of electron, but would still like to take advantage of other improvements in meteor-desktop

**Comment by wojtkowiak** [comment]
This should land soon on 2.0

**Comment by KoenLav** [comment]
@wojtkowiak I just tested this functionality creating a build of our application running on Electron 3.0.3 and it worked flawlessly.

Will be testing in the wild soon, but I'm not expecting significant difficulties.

I guess we can mark this complete!
