### ISSUE TITLE
Passing callback function using Desktop.send doesn't seem to work

### ISSUE THREAD

**Issue by sferoze** [wojtkowiak/meteor-desktop#170]
I am using Desktop.send to communicate with Electron from client javascript. I am following the example. 

`Desktop.send('localStorage', 'set', key, value)`

When value is a string, or number, Electron receives this value just fine. But if value is a function, it is received as null. 

So how can we pass a callback function to Electron side? Or can we only pass values? 

I want to pass a callback function so I can return a value to client side.

**Comment by sferoze** [comment]
Or is it possible to send the native inAppPurchase module from Electron to the client using Desktop.fetch?

**Comment by sferoze** [comment]
@KoenLav 

Can you elaborate, or provide me with a link to an example of an implementation that relies on IPC like you mentioned?

**Comment by wojtkowiak** [comment]
You need to set the callbacks in the main process and proxy their invocation over IPC.

```javascript
// desktop.js

inapppurchase.on('transactions-updated', (...args) => {
  this.module.send('transaction-updated', ...args);
});

// meteor side

Desktop.on('desktop', 'transaction-updated', (event, ...args) => {

});
```

**Comment by wojtkowiak** [comment]
@sferoze do you need any more help?

**Comment by sferoze** [comment]
@wojtkowiak I will be trying this today and will let you know...

But basically, it looks like I can send data to client-side using events?

in my case an example would be

```
// meteor side

           Desktop.send('desktop', 'getReceipt')

// desktop.js

            desktop.on('getReceipt', () => {
              inAppPurchase.getReceiptURL().then((receipt) => {
                _receipt = receipt;
                this.module.send('transaction-updated', receipt);
             }, (err) => {
                console.log(err, 'error');
                return _receipt;
              });
            });

// meteor side

        Desktop.on('desktop', 'getReceipt', (event, ...args) => {} )
```

Does this look correct?

**Comment by wojtkowiak** [comment]
@sferoze from what you've wrote it looks more like a classic request/response case so definitely using `fetch` will be easier. 

```
// meteor side

Desktop.fetch('desktop', 'getReceipt', 20000)
    .then(response => {})
   .catch(console.error);

// desktop.js

            this.module.on('getReceipt', (event, fetchId) => {
              inAppPurchase.getReceiptURL().then((receipt) => {
                _receipt = receipt;
                this.module.respond('getReceipt', fetchId, receipt);
             }, (err) => {
                this.module.respond('getReceipt', fetchId, false);
              });
            });
```

**Comment by wojtkowiak** [comment]
Can this be closed?
