### ISSUE TITLE
secure origins 127.0.0.1 to meteor:// 

### ISSUE THREAD

**Issue by aboire** [wojtkowiak/meteor-desktop#174]
the change in version 1 from 127.0.0.1 to meteor: // will cause a problem when using features that require a secure origins

**Comment by wojtkowiak** [comment]
Do you know if there's a list of features that require secure origin?

**Comment by aboire** [comment]
yes https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins

Geolocation — requires secure origins as of M50
Device motion / orientation
EME
getUserMedia
AppCache
Notifications

**Comment by aboire** [comment]
I use Geolocation and Notification with version 0.18.1 in my app and no problem with 127.0.0.1 because considered secure as localhost

**Comment by aboire** [comment]
I see a flag --unsafely-treat-insecure-origin-as-secure I do not know if that can be the solution

**Comment by wojtkowiak** [comment]
I will be checking that thoroughly tomorrow.
Have you actually tested with `1.0.0` if your geolocation still works?

**Comment by aboire** [comment]
yes geolocation not work

**Comment by wojtkowiak** [comment]
Can you paste the error you get on the console?

**Comment by wojtkowiak** [comment]
Ok, I confirm the problem. Should be fixed today.

**Comment by aboire** [comment]
yes it's good for me thank
