### ISSUE TITLE
Error: error while trying to require uglify-es, are you sure you have meteor-desktop installed

### ISSUE THREAD

**Issue by trukhilio** [wojtkowiak/meteor-desktop#189]
Hi,
I'm using a meteor-launch for building my mobile app and meteor-desktop for desktop app. These days after the meteor-desktop had been updated from 1.5.0 to 1.6.0 version I received this error on meteor-launch build command:

`[meteor-desktop] creating a production build -
Errors prevented bundling:                    
While processing files with omega:meteor-desktop-bundler (for target web.cordova):
version.desktop: Error: error while trying to require uglify-es, are you sure you have meteor-desktop installed?`

Meteor version 1.6.1.1
When I update to prev version 1.5.0 - all is fine. Also updated all npm packages and meteor to the latest on this moment 1.7.0.3 release and received the same error on a meteor startup. So, I can't run even my app.
Could anyone say how to fix it? 
Thanks

**Comment by wojtkowiak** [comment]
Hey,

check if in `.meteor` packages you have the meteor-desktop bundler and watcher at `@=1.6.0`. It seems like you are using 1.6.0 but the plugins did not update.
You can also just run `npm run desktop` without meteor running and it will update the plugins versions automatically.

**Comment by trukhilio** [comment]
Hi,
Yeah, it helped! I had old packages `@=1.5.0`.
You are right, after npm module updated it is better to run the meteor-desktop before any build with it to update meteor dependent packages. Maybe this rule is also useful to similar libs where npm module has a meteor dependent packages.
I appreciate what are you doing! Keep moving! Thanks a lot!

**Comment by wojtkowiak** [comment]
Ok, glad it was it. I'll add a check in the bundler plugin so instead of failing it will tell you that it's in a different version than in package.json 🙂
