### ISSUE TITLE
Desktop HCP vs Cordova

### ISSUE THREAD

**Issue by KoenLav** [wojtkowiak/meteor-desktop#190]
@wojtkowiak 

It seems HCP has now been properly fixed for meteor-desktop (Electron), but in Meteor Cordova most people are still experiencing issues.

Have you been able to create a fork of the cordova-plugin-meteor-webapp repository which fixes these issues entirely?

If so, would you care to share the branch you are currently on?

If not, would you like to work together on creating a solution for these problems?

Or at least provide some pointers on how you fixed these issues in meteor-desktop?

Apologies for 'hijacking' an issue on this repo for these questions! I just figured if you were able to fix it in Electron, same should be possible for Cordova :)

**Comment by wojtkowiak** [comment]
@KoenLav sorry for not replying in other tasks.

> Have you been able to create a fork of the cordova-plugin-meteor-webapp repository which fixes these issues entirely?

Well at the moment we have a fork containing all the other fixes scattered on different forks baked with changes for an update screen feature. Let's say I am satisfied with how it works and the client did not report any new problems with HCP in our product. I did want to prepare PRs but that landed with low priority in the backlog. 

But the good news are that finally I have scheduled it to be picked up next week as I want to limit the number of forks used in the project. So I should update or create PRs in the webapp plugin next week.

**Comment by KoenLav** [comment]
Hi @wojtkowiak, thanks for your prompt reply! Not a problem, we're all busy with our projects/businesses as well of course ;)

Could you maybe point me to this fork? I'd love to give it a try (also to find out which of the fixes actually resolve the issues).

If I, or anyone else in our company (we have some people more focused on native (Java/Swift) development) can help out in any way, make sure to let me know!

**Comment by KoenLav** [comment]
Friendly ping!

**Comment by KoenLav** [comment]
@wojtkowiak friendly ping!

**Comment by KoenLav** [comment]
PRs have been provided in the cordova-plugin-meteor-webapp repo!
