### ISSUE TITLE
[Request] allow devTools with --production

### ISSUE THREAD

**Issue by lunafi-evan** [wojtkowiak/meteor-desktop#196]
It would be helpful to be able to build a production build using electron-builder that can have devtools enabled, so that we can debug any discrepancies between the dev and prod desktop build. Perhaps an env var

```
ELETRON_DEV_TOOLS_PRODUCTION=true meteor run --mobile-server=127.0.0.1:3000
```

**Comment by lunafi-evan** [comment]
thanks for getting this in!

**Comment by wojtkowiak** [comment]
No problem, sorry you had to wait for it and thanks for your effort in the PR!
