### ISSUE TITLE
expose file system over /local-filesystem

### ISSUE THREAD

**Issue by wojtkowiak** [wojtkowiak/meteor-desktop#20]
Prepare an equivalent of https://guide.meteor.com/mobile.html#accessing-local-files

**Comment by met5678** [comment]
:+1: This would be extremely helpful for a video-based app I'm working on.

**Comment by wojtkowiak** [comment]
@met5678 this is available now in `0.3.0` [check here](https://github.com/wojtkowiak/meteor-desktop#accessing-local-filesystem-in-meteor)

**Comment by met5678** [comment]
@wojtkowiak Awesome, thanks so much! Will check it out tonight.
