### ISSUE TITLE
Save file dialog

### ISSUE THREAD

**Issue by maasha** [wojtkowiak/meteor-desktop#200]
I am developing an app that needs a save file dialog. Electron have a dialog that goes something like this:

```
const { dialog } = require('electron').remote;

dialog.showSaveDialog((file) => {
  if (file === undefined) {
    console.log("You didn't save the file");
    return;
  }

  fs.writeFileSync(file, content, 'utf8');
});
```

I would like to develop the app using Meteor and testing it in the browser before creating the app bundle, however, that causes issues with the local file access being denied by the browser.

Suggestions on how to proceed with a save file dialog?

**Comment by iehdk** [comment]
Nevermind, it turns out that the Electronification converts a standard download into a save as dialog. Great

**Comment by maasha** [comment]
Aha, the Electronification process turns a standard download into a "save as" dialog. Great!
