### ISSUE TITLE
TypeError: Detail must be a string

### ISSUE THREAD

**Issue by dnish** [wojtkowiak/meteor-desktop#21]
Hey,
my desktop app suddenly stopped working. I'm getting the following error:

``` 
error: [main]  Error: ENOENT, _desktop.json not found in /Users/dennis/Desktop/Entwicklung/yb/yb-web/.meteor/desktop-build/meteor.asar
    at notFoundError (ELECTRON_ASAR.js:120:19)

TypeError: Detail must be a string
    at Object.showMessageBox (/Users/dennis/Desktop/Entwicklung/yb/ybt-web/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/dialog.js:162:13)
```

**Comment by wojtkowiak** [comment]
> TypeError: Detail must be a string

Apparently there is bug in the scaffold, please change your code according to this: https://github.com/wojtkowiak/meteor-desktop/commit/1dc8347f18d2ebc1dfb3f875a66e1d5206441af8

> Error: ENOENT, _desktop.json not found

What do you mean by "suddenly"? It happened after some particular changes?

Please post log from build and your settings.json. Also let me know what system, meteor version and meteor-desktop version you are using.

**Comment by dnish** [comment]
Yes, If I remember right, it happens after I install an NPM package while the app is running. I had to remove the whole desktop project and readded it again. If it happens again, I'll post the logs.

I'm running on macOS Sierra, Meteor 1.4.2 and meteor-desktop 0.1.3

**Comment by dnish** [comment]
Didn't happen again, so I think this was an internal issue. Closing it because I can't reproduce it again.
