### ISSUE TITLE
Electron 4.0.1 Meteor bundle cut-off at random (seemingly)

### ISSUE THREAD

**Issue by KoenLav** [wojtkowiak/meteor-desktop#220]
When running meteor-desktop 2.0 with Meteor 1.8 and Electron 4.0.1 it seems the bundle gets cut off at at random point, rendering execution errors when using npm run desktop.

I realize this version is not yet supported, but just wanted to see whether others are experiencing the same issue or it is specific to our setup.

Electron 3.0.14 works just fine, with the same setup.

**Comment by KoenLav** [comment]
Likely to be related to: https://github.com/electron/electron/issues/16213

**Comment by vladimiry** [comment]
If you don't serve really huge files, I guess `registerBufferProtocol` can be a reliable replacement for `registerStreamProtocol`, so you serve the data as a whole piece, https://github.com/electron/electron/issues/13519#issuecomment-449504303.

**Comment by KoenLav** [comment]
@vladimiry thanks!

@wojtkowiak any specific reason you decided to use registerStreamProtocol over, for instance, registerBufferProtocol (or one of the other available register......Protcol functions)?

**Comment by sferoze** [comment]
Just wanted to say that I also did try Electron 4.0 and could not get it to work. When building it would error out, and I thought it had to do with babel not compiling something correctly. 

But Electron 3.0 works fine

**Comment by KoenLav** [comment]
This has been resolved with Electron 4.0.3 (registerStreamProtocol fix).
