### ISSUE TITLE
How to create context menu

### ISSUE THREAD

**Issue by stocksp** [wojtkowiak/meteor-desktop#24]
This is very easy to do in 'straight up' Electron' (from the docs) [http://electron.atom.io/docs/api/menu/#render-process](url)  ... not so obvious here in Meteor land.
```
<!-- index.html -->
<script>
const {remote} = require('electron')
const {Menu, MenuItem} = remote

const menu = new Menu()
menu.append(new MenuItem({label: 'MenuItem1', click() { console.log('item 1 clicked') }}))
menu.append(new MenuItem({type: 'separator'}))
menu.append(new MenuItem({label: 'MenuItem2', type: 'checkbox', checked: true}))

window.addEventListener('contextmenu', (e) => {
  e.preventDefault()
  menu.popup(remote.getCurrentWindow())
}, false)
</script>
```

I thought maybe I could do this in Meteor startup with a
```
if (Meteor.isDesktop) {
    console.log('in desktop startup');
    var remote = require('electron').remote; //<-- crash here
    var Menu = remote.Menu;
    var MenuItem = remote.MenuItem;
```

but this fails with a
fs.readFileSync is not a function ... coming from module js.

I could not see how to get hold of the document window from any of the events Desktop has (like 'windowCreated'  --wrong kind of window) .... help!

**Comment by wojtkowiak** [comment]
`nodeIntegration` is disabled in `meteor-desktop` for security reasons so you can not `require` in meteor app.
But there should be no problem at all to add this menu from the renderer process. 
In the `desktop.js` you can `import { Menu } from 'electron';` and create your menu.
and in the `windowCreated` you can do something like:
```javascript
 eventsBus.on('windowCreated', (window) => {
      window.webContents.on('contextmenu', () => {
          menu.popup(window);
      });
});

**Comment by stocksp** [comment]
excellent!
