### ISSUE TITLE
_this.packager is not a function

### ISSUE THREAD

**Issue by gunnartorfis** [wojtkowiak/meteor-desktop#248]
I'm not sure if this is a bug with meteor-desktop or electron-packager - or if I'm doing something wrong.

I run my app locally with:
`meteor --mobile-server=127.0.0.1:3000` in one tab
and in another tab
`npm run desktop -- --scaffold`
And everything works as you'd expect.

But when I try to package my application to .app/.exe using 
`npm run desktop -- package`
I get an error:

> ERROR  index:  while trying to build a package an error occurred: TypeError: _this.packager is not a function

Am I missing something?

**Comment by darqs** [comment]
Hello @gunnartorfis,

I fixed the problem with import, but I don't know when it will be released

**Comment by wojtkowiak** [comment]
Try now with `v2.2.4`

**Comment by wojtkowiak** [comment]
not sure if this is still relevant for you but should be fixed in 2.2.5

**Comment by gunnartorfis** [comment]
Thanks! That did the job 👏
