### ISSUE TITLE
Build cannot connect to sockjs only in production builds during --build-meteor

### ISSUE THREAD

**Issue by lacymorrow** [wojtkowiak/meteor-desktop#249]
My Meteor project loads fine running `npm run meteor-desktop --production` but after building using `npm run meteor-desktop build-installer --build-meteor --mac --production`

My front-end loads but receives errors connecting to `localhost:3000/sockjs?...`

Any ideas?

**Comment by lacymorrow** [comment]
![image](https://user-images.githubusercontent.com/1311301/68349225-467c8b00-00b1-11ea-95b3-ab6a94bd148a.png)

**Comment by wojtkowiak** [comment]
> https://github.com/wojtkowiak/meteor-desktop/issues/250
