### ISSUE TITLE
desktop.js ignored in final build?

### ISSUE THREAD

**Issue by dnish** [wojtkowiak/meteor-desktop#25]
Hey,
I'm having some trouble with my generated DMG build. It seems like that the content I've added into <code>.desktop/desktop.js</code> is fully ignored. In the development app, everything is working fine, but in the production app, nothing seems to work.

For example, I'm adding some shortcuts or change the windows size:

    eventsBus.on('windowCreated', (window) => {

            // Setting perfect size
            window.setSize(1024,768);

            window.webContents.on('crashed', Desktop.windowCrashedHandler);
            window.on('unresponsive', Desktop.windowUnresponsiveHandler);

        });

```
  globalShortcut.register('MediaPreviousTrack', () => {
         ....
        });
```

**Comment by dnish** [comment]
Just tried to move that code into an own module. Got the same behavior: Everything is working on <code>meteor run desktop</code>, but failing if I create the installer and run the production app.

**Comment by dnish** [comment]
Just did some additional test, maybe you can reproduce it:

Add the following to the constructor of your <code>.desktop/desktop.js</code> file:

     setTimeout(() => {  app.quit(); },5000);

Then run <code>npm run desktop</code>. The window will close after 5 seconds. Then do the same with <code>npm run desktop -- package</code>, open the generated .dmg file. The window will not close after 5 minutes.

**Comment by wojtkowiak** [comment]
Sorry for late answer.
I did try to reproduce it but it works fine on my Mac.
Are you sure you are unmounting the dmg before you run `build-installer` again? You need to be sure the `dmg` file is not locked. I noticed that sometime `electron-builder` silently fails to update that file. 
Are installing the app from the `.dmg` or do you try to run it directly from the `.dmg`? Does the same happens to the app not packed into `.dmg`?

**Comment by dnish** [comment]
@wojtkowiak I'm just running <code>npm run desktop -- build installer</code> and then open <code>/.desktop-installer/mac/MyApp-1.0.0.dmg</code>. What do you exactly mean by "locked"? If I run <code>npm run desktop</code>, I can't find any mounted .dmg file.

**Comment by wojtkowiak** [comment]
But when you open a `.dmg` file, what is actually happening is that the `.dmg` is mounted and the contents of it are displayed. DMG stands for Apple Disk Image, and as an image it needs to be mounted before read. On your desktop you should see an icon representing the mounted volume.
Upon right click there is a menu with "unmount" displayed and you should do that before invoking `build-installer` once again.
Also you should not try to run the app directly from the `.dmg` without copying it to your Applications.

**Comment by dnish** [comment]
Okay, just tried it by mounting the .dmg file and then moving my app into Applications.  Got the same behavior: The window doesn't resize and the keyboard shortcuts aren't working, while they are working in development mode fine. Are there any settings I need to set within settings.json to register my internal modules? Maybe I've forgot something.

**Comment by dnish** [comment]
Strange, there it works fine.

**Comment by dnish** [comment]
@wojtkowiak Finally got it: I didn't add a dependency for <code>electron-dl</code> within my module.json, instead I've added it to Meteor's package.json. 

But after multiple rebuilds I found another issue: My .dmg sizes increases in size (about 10MB) after every installer build.

**Comment by wojtkowiak** [comment]
Good to hear that you have solved it. 
> But after multiple rebuilds I found another issue: My .dmg sizes increases in size (about 10MB) after every installer build. 
Would you be able to investigate it further? Could you unpack both .dmg and check what actually changed its size?
