### ISSUE TITLE
"Built" desktop app cannot connect to server. `--production` flag works.

### ISSUE THREAD

**Issue by lacymorrow** [wojtkowiak/meteor-desktop#250]
Testing with a fresh Meteor project that makes a single `Meteor.call()` to the server for a response.

Running `meteor-desktop --production` works as expected but after building the app with `meteor-desktop --build-installer` and running the executable, the client errors trying to connect to `:3000/sockjs/...`.

This effectively makes `meteor-desktop` useless, since generating the final installer is the goal of using this package.

**Comment by wojtkowiak** [comment]
Hey,

are you trying to connect to your local meteor server with production build? That will only work if you have the `meteor` running with `--production`

**Comment by lacymorrow** [comment]
@wojtkowiak Thank you for responding!

Would it be possible to allow me contributor access to this project?
I love the project and would like to keep it alive for you :)

**Comment by wojtkowiak** [comment]
@lacymorrow I am open to add new contributors to this project but first a person needs to demonstrate some knowledge of this package by providing some PRs, help triage the issues etc
I will try to build a wider team for this package this year so I'll reach out to you within next months.

**Comment by wojtkowiak** [comment]
Is this issue still relevant?

**Comment by lacymorrow** [comment]
Thanks @wojtkowiak, I believe this can be closed. I'll look into some of the more pressing issues and try to put together a couple of PRs in the coming weeks

Cheers!
