### ISSUE TITLE
TCP connections not working in production

### ISSUE THREAD

**Issue by gunnartorfis** [wojtkowiak/meteor-desktop#251]
My app needs to make TCP connections to a card reader (terminal) on localhost. That's the sole reason we want to use meteor-desktop. It works perfectly when running in development but once we build a production build and run the .app, no connections are established. Neither on macOS nor Windows.

For the task we're using the net package and create a new socket using 
`let client = new net.Socket();`
Then we connect to the terminal using the subnet IP, e.g. 192.168.1.224 and port 10676. 

Are there any configurations I'm missing to allow TCP connections or something I need to use that specific port?

**Comment by wojtkowiak** [comment]
Hey,

where is your code placed?
`let client = new net.Socket();` is this line inside `.desktop`?

**Comment by gunnartorfis** [comment]
Thanks for the reply! Here's an abstracted version of my module:
```
import net from 'net';
import convert from 'xml-js';
import axios from 'axios';
import { print } from 'graphql';
import gql from 'graphql-tag';
import logger from 'electron-log';
import moduleJson from './module.json';

let client = new net.Socket();

export default class Terminal {
  constructor({ log, skeletonApp, appSettings, eventsBus, modules, settings, Module }) {
  
  this.module.on('initiatePayment', (event, fetchId, payload) => {
    client.connect(PORT, IP_ADDRESS, () => {
       ....
    });
  });
  
  init() {
    this.eventsBus.emit(`${moduleJson.name}.loaded`);
  }
}
```

**Comment by wojtkowiak** [comment]
Ok, I do not see anything wrong here in particular. Have you caught anything in the run.log (C:\Users\XXX\AppData\Roaming\YourAppName\run.log) ?
I can investigate the problem directly but I would be super grateful if you could just prepare an empty meteor project with just that code above (smallest reproduction possible). I've searched a little bit for electron/node bugs but did not find anything related.
Is the the IP/PORT coming from any configuration, check if you are getting the proper config after you build production version - just a wild guess? You can use the `log` and you will find your module's log along the `run.log`

**Comment by gunnartorfis** [comment]
I will have a look at the logs and recreate the issue with an empty Meteor project.

**Comment by gunnartorfis** [comment]
We've investigated the issue thoroughly and found out that if we import/require _any_ NPM package we installed via `meteor npm install`, our module doesn't work at all (the module is listed in the project's root package.json). When we comment out the import, the module works. 

We've tried two NPM packages to import, xml-js and axios. So it's probably not an issue with a single package. 

How are we suppose to use packages installed via NPM/Yarn?

**Comment by gunnartorfis** [comment]
I figured out a solution, not optimal but it works.
What I was trying to accomplish was to convert XML to JSON using the xml-js package. 
I solved it by using `fetch` on Electron side, passing the XML and converting it on the Meteor side and then responding with the fetchId back to Electron.

**Comment by wojtkowiak** [comment]
I am still not exactly sure how did you try to do this.

> if we import/require any NPM package we installed via meteor npm install, our module doesn't work at all (the module is listed in the project's root package.json).

If by `module` you think about desktop module that resides in `.desktop/modules/` then it should not be possible to import a package you have only declared in meteor project's package.json. If you want to import a package inside `.desktop` you need to add it to dependencies in `settings.json` or directly in the `module.json` like this: 
```
{
    "name": "myModule",
    "dependencies": {
        "npmpackage": "2.0.0"
    }
}
```

**Comment by wojtkowiak** [comment]
Glad that you've found a workaround but I am still interested to find a root cause of this :)

**Comment by gunnartorfis** [comment]
Ah. I didn't include the dependency in the module.json file 🤦‍♂.
