### ISSUE TITLE
modifying entitlements for signing a sandboxed app for mac app store distribution

### ISSUE THREAD

**Issue by LDubya** [wojtkowiak/meteor-desktop#259]
Hello, how do we modify the entitlements for the mac build?

By default, it signs with the following entitlements:

`com.apple.security.cs.allow-unsigned-executable-memory : TRUE`
`com.apple.security.cs.disable-library-validation : TRUE`

which seem to be sufficient for distribution outside of the Mac App store. However Apple requires that apps signed for distribution within the mac app store *not* have the above entitlements, and instead at least have the following entitlement, which makes it a sandboxed app: 

`com.apple.security.app-sandbox : TRUE`

But I'm not sure where to go to modify the entitlements that will be used for packaging the app. After doing a grep for the default entitlements, I find them inside the `node_modules/app-builder-lib/templates/entitlements.mac.plist` file. However, I don't want to modify a node module, since it can be overwritten. Is there a settings file that we are supposed to use to set entitlements?

**Comment by LDubya** [comment]
for now I ended up hard-coding it inside the `node_modules/app-builder-lib/templates/entitlements.mac.plist`, but that feels super hacky

**Comment by dorian-coygo** [comment]
I think that app-builder-lib is from electron right https://www.electron.build/configuration/mac ? I'm pretty sure the .desktop/settings.json you could set the correct settings, but not 100% sure.

**Comment by LDubya** [comment]
It looks like the package only supports a subset of what's in that documentation. the 'entitlements' option is not supported. Setting it leads to the following error:

```
ERROR  electronBuilder:  error while building installer:  { ValidationError: Invalid configuration object. electron-builder 21.2.0 has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'entitlements'. These properties are valid:
   object { afterAllArtifactBuild?, afterPack?, afterSign?, apk?, appId?, appImage?, appx?, artifactBuildCompleted?, artifactBuildStarted?, artifactName?, asar?, asarUnpack?, beforeBuild?, buildDependenciesFromSource?, buildVersion?, compression?, copyright?, cscKeyPassword?, cscLink?, deb?, detectUpdateChannel?, directories?, dmg?, electronCompile?, electronDist?, electronDownload?, electronUpdaterCompatibility?, electronVersion?, extends?, extraFiles?, extraMetadata?, extraResources?, fileAssociations?, files?, forceCodeSigning?, framework?, freebsd?, generateUpdatesFilesForAllChannels?, icon?, includePdb?, launchUiVersion?, linux?, mac?, mas?, msi?, nodeGypRebuild?, nodeVersion?, npmArgs?, npmRebuild?, nsis?, nsisWeb?, onNodeModuleFile?, p5p?, pacman?, pkg?, portable?, productName?, protocols?, publish?, readonly?, releaseInfo?, remoteBuild?, removePackageScripts?, rpm?, snap?, squirrelWindows?, target?, win?, $schema? }
```

**Comment by LDubya** [comment]
@dorian-coygo that did the trick
