### ISSUE TITLE
Can we disable .zip building?

### ISSUE THREAD

**Issue by dnish** [wojtkowiak/meteor-desktop#26]
Hey,
just want to know if I can disable the building of a ZIP file when I run <code>npm run desktop -- build-installer</code>?

**Comment by wojtkowiak** [comment]
Yes,
just add `target: ["dmg"]` to `mac` section of `builderOptions` --> https://github.com/electron-userland/electron-builder/wiki/Options#buildmac

**Comment by wojtkowiak** [comment]
Can this be closed?
