### ISSUE TITLE
missing script: desktop

### ISSUE THREAD

**Issue by sasikanth513** [wojtkowiak/meteor-desktop#30]
I'm trying to use this with default meteor todos app, when I run `npm run desktop -- init` it is throwing ```missing script: desktop``` error

![screen shot 2016-11-29 at 1 52 25 pm](https://cloud.githubusercontent.com/assets/6153816/20702016/f6fa5dfe-b63b-11e6-8886-deef79fffb3c.png)

this is how my package.json file looks like after i done ```meteor npm install --save-dev meteor-desktop```. I tried to add electron as devdependency also installed it globally

```
"scripts": {
    "start": "meteor",
    "pretest": "npm run lint --silent",
    "test": "meteor test --once --driver-package dispatch:mocha-phantomjs",
    "test-app": "meteor test --full-app --once --driver-package dispatch:mocha-phantomjs",
    "test-watch": "meteor test --driver-package practicalmeteor:mocha",
    "test-app-watch": "meteor test --full-app --driver-package practicalmeteor:mocha",
    "test-watch-terminal": "TEST_WATCH=1 meteor test --driver-package dispatch:mocha-phantomjs",
    "test-app-watch-terminal": "TEST_WATCH=1 meteor test --full-app --driver-package dispatch:mocha-phantomjs",
    "lint": "eslint ."
  },
  "dependencies": {
    "autoprefixer": "^6.4.1",
    "babel-runtime": "^6.18.0",
    "faker": "^3.0.1"
  },
  "devDependencies": {
    "babel-eslint": "^6.1.2",
    "electron": "^1.4.10",
    "eslint": "^3.5.0",
    "eslint-config-airbnb": "^11.1.0",
    "eslint-import-resolver-meteor": "^0.3.3",
    "eslint-plugin-import": "^1.15.0",
    "eslint-plugin-jsx-a11y": "^2.2.2",
    "eslint-plugin-meteor": "^4.0.0",
    "eslint-plugin-react": "^6.2.2",
    "meteor-desktop": "^0.2.1",
    "shell-source": "^1.1.0",
    "shelljs": "^0.7.4"
  }
```

As error suggests there is no `desktop` script inside package.json? am I doing something wrong?

**Comment by wojtkowiak** [comment]
Are you sure that `meteor install --save-dev meteor-desktop` succeeded? Because it seems that if failed to add itself to your scripts section.
Please run `meteor install --save-dev meteor-desktop` again and check it this time.
If it ends with an error or succeeds but the `desktop` is still missing please paste the log here.
You can try to add it manually - just add `"desktop": "meteor-desktop"` to your scripts section.

**Comment by sasikanth513** [comment]
adding manually worked. 👍
