### ISSUE TITLE
Fail to run on Windows 10

### ISSUE THREAD

**Issue by nizulzaim** [wojtkowiak/meteor-desktop#31]
Hi, I dont know what is wrong but i do know that i cannot add android platform because of Meteor are not supporting it. Everything i have done including just running `meteor` not show sign of success. Here is my error log. 

```
INFO  meteorApp:  successfully downloaded index.html from running meteor app
ERROR  meteorApp:  no mobile build found at Z:\DevsignStudio\peper\.meteor\local\build\programs\web.cordova
ERROR  meteorApp:  are you sure you did run meteor with --mobile-server?

npm ERR! Windows_NT 10.0.14965
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "desktop"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! peper2@ desktop: `meteor-desktop`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the peper2@ desktop script 'meteor-desktop'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the peper2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     meteor-desktop
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs peper2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls peper2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     Z:\DevsignStudio\peper\npm-debug.log
```

**Comment by nizulzaim** [comment]
before you ask me how i run it, I run it both on `meteor npm` and also `npm`. My meteor version is METEOR@1.4.2.3

**Comment by AdityaDinesh** [comment]
I get the same error on Windows 10 with Meteor 1.4.2.3. Are you able to resolve this on your machine?

**Comment by sasikanth513** [comment]
@AdityaDinesh @nizulzaim As mentioned in the error, you should run meteor app using `meteor --mobile-server=127.0.0.1:3000` and make sure at least one of `android` or `ios` platform is added.

**Comment by nizulzaim** [comment]
Sorry, my mistake.. i do have this problem and then i found solution to integrate android sdk with meteor. Thats why i closed this issue but sorry i dont post how to integrate it. I'm on mobile, i will post workaround here so that everyone can do as reference
