### ISSUE TITLE
It don't works fine like browser to upload file

### ISSUE THREAD

**Issue by marryton007** [wojtkowiak/meteor-desktop#32]
We developing a project base on [meteor-starter](https://github.com/yogiben/meteor-starter) , and use [meteor-collectionfs](CollectionFS/Meteor-CollectionFS) to save upload images, it works fine with browser,  but it can't correctly work on meteor-desktop.  

meteor version:  METEOR@1.3.5.1

error messages from the electron devtools while uploading a image:

You called Router.path for a route named "adminDashboardNew" but that route doesn't seem to exist. Are you sure you created it?
http://127.0.0.1:8053/admin/Corporations/new Failed to load resource: the server responded with a status of 404 (Not Found)
cfs_upload-http.js:109The provided value 'undefined' is not a valid enum value of type XMLHttpRequestResponseType.
http://127.0.0.1:8053/cfs/files/attachments/uMSsdDZyjpt7zRJw7?chunk=0&filen…VG9rZW4iOiJrZjIwaTVpZVFDTXZ0dmZaZ3BRdTVwcWMzNURlaUd2SWZROVNoY0FUVFNlIn0%3D Failed to load resource: the server responded with a status of 404 (Not Found)
cfs_power-queue.js:494Error: "Queue" failed [404] Cannot PUT /cfs/files/attachments/uMSsdDZyjpt7zRJw7?chunk=0&amp;filename=2015-12-29-1036391643.jpg&amp;token=eyJhdXRoVG9rZW4iOiJrZjIwaTVpZVFDTXZ0dmZaZ3BRdTVwcWM... [undefined], Error: failed [404] Cannot PUT /cfs/files/attachments/uMSsdDZyjpt7zRJw7?chunk=0&amp;filename=2015-12-29-1036391643.jpg&amp;token=eyJhdXRoVG9rZW4iOiJrZjIwaTVpZVFDTXZ0dmZaZ3BRdTVwcWM... [undefined]
    at cfs_upload-http.js:351
    at cfs_upload-http.js:77
    at underscore.js:750
    at XMLHttpRequest.xhr.onreadystatechange (cfs_upload-http.js:200)PowerQueue.runTaskDone @ cfs_power-queue.js:494
cfs_upload-http.js:109The provided value 'undefined' is not a valid enum value of type XMLHttpRequestResponseType.
http://127.0.0.1:8053/cfs/files/attachments/uMSsdDZyjpt7zRJw7?chunk=0&filen…VG9rZW4iOiJrZjIwaTVpZVFDTXZ0dmZaZ3BRdTVwcWMzNURlaUd2SWZROVNoY0FUVFNlIn0%3D Failed to load resource: the server responded with a status of 404 (Not Found)
cfs_power-queue.js:494Error: "Queue" failed [404] Cannot PUT /cfs/files/attachments/uMSsdDZyjpt7zRJw7?chunk=0&amp;filename=2015-12-29-1036391643.jpg&amp;token=eyJhdXRoVG9rZW4iOiJrZjIwaTVpZVFDTXZ0dmZaZ3BRdTVwcWM... [undefined], Error: failed [404] Cannot PUT /cfs/files/attachments/uMSsdDZyjpt7zRJw7?chunk=0&amp;filename=2015-12-29-1036391643.jpg&amp;token=eyJhdXRoVG9rZW4iOiJrZjIwaTVpZVFDTXZ0dmZaZ3BRdTVwcWM... [undefined]
    at cfs_upload-http.js:351
    at cfs_upload-http.js:77
    at underscore.js:750
    at XMLHttpRequest.xhr.onreadystatechange (cfs_upload-http.js:200)PowerQueue.runTaskDone @ cfs_power-queue.js:494
cfs_upload-http.js:109The provided value 'undefined' is not a valid enum value of type XMLHttpRequestResponseType.
http://127.0.0.1:8053/cfs/files/attachments/uMSsdDZyjpt7zRJw7?chunk=0&filen…VG9rZW4iOiJrZjIwaTVpZVFDTXZ0dmZaZ3BRdTVwcWMzNURlaUd2SWZROVNoY0FUVFNlIn0%3D Failed to load resource: the server responded with a status of 404 (Not Found)
cfs_power-queue.js:494Error: "Queue" failed [404] Cannot PUT /cfs/files/attachments/uMSsdDZyjpt7zRJw7?chunk=0&amp;filename=2015-12-29-1036391643.jpg&amp;token=eyJhdXRoVG9rZW4iOiJrZjIwaTVpZVFDTXZ0dmZaZ3BRdTVwcWM... [undefined], Error: failed [404] Cannot PUT /cfs/files/attachments/uMSsdDZyjpt7zRJw7?chunk=0&amp;filename=2015-12-29-1036391643.jpg&amp;token=eyJhdXRoVG9rZW4iOiJrZjIwaTVpZVFDTXZ0dmZaZ3BRdTVwcWM... [undefined]
    at cfs_upload-http.js:351
    at cfs_upload-http.js:77
    at underscore.js:750
    at XMLHttpRequest.xhr.onreadystatechange (cfs_upload-http.js:200)PowerQueue.runTaskDone @ cfs_power-queue.js:494
cfs_upload-http.js:109The provided value 'undefined' is not a valid enum value of type XMLHttpRequestResponseType.
http://127.0.0.1:8053/cfs/files/attachments/uMSsdDZyjpt7zRJw7?chunk=0&filen…VG9rZW4iOiJrZjIwaTVpZVFDTXZ0dmZaZ3BRdTVwcWMzNURlaUd2SWZROVNoY0FUVFNlIn0%3D Failed to load resource: the server responded with a status of 404 (Not Found)
cfs_power-queue.js:494Error: "Queue" failed [404] Cannot PUT /cfs/files/attachments/uMSsdDZyjpt7zRJw7?chunk=0&amp;filename=2015-12-29-1036391643.jpg&amp;token=eyJhdXRoVG9rZW4iOiJrZjIwaTVpZVFDTXZ0dmZaZ3BRdTVwcWM... [undefined], Error: failed [404] Cannot PUT /cfs/files/attachments/uMSsdDZyjpt7zRJw7?chunk=0&amp;filename=2015-12-29-1036391643.jpg&amp;token=eyJhdXRoVG9rZW4iOiJrZjIwaTVpZVFDTXZ0dmZaZ3BRdTVwcWM... [undefined]
    at cfs_upload-http.js:351
    at cfs_upload-http.js:77
    at underscore.js:750
    at XMLHttpRequest.xhr.onreadystatechange (cfs_upload-http.js:200)PowerQueue.runTaskDone @ cfs_power-queue.js:494
cfs_upload-http.js:109The provided value 'undefined' is not a valid enum value of type XMLHttpRequestResponseType.
http://127.0.0.1:8053/cfs/files/attachments/uMSsdDZyjpt7zRJw7?chunk=0&filen…VG9rZW4iOiJrZjIwaTVpZVFDTXZ0dmZaZ3BRdTVwcWMzNURlaUd2SWZROVNoY0FUVFNlIn0%3D Failed to load resource: the server responded with a status of 404 (Not Found)
cfs_power-queue.js:494Error: "Queue" failed [404] Cannot PUT /cfs/files/attachments/uMSsdDZyjpt7zRJw7?chunk=0&amp;filename=2015-12-29-1036391643.jpg&amp;token=eyJhdXRoVG9rZW4iOiJrZjIwaTVpZVFDTXZ0dmZaZ3BRdTVwcWM... [undefined], Error: failed [404] Cannot PUT /cfs/files/attachments/uMSsdDZyjpt7zRJw7?chunk=0&amp;filename=2015-12-29-1036391643.jpg&amp;token=eyJhdXRoVG9rZW4iOiJrZjIwaTVpZVFDTXZ0dmZaZ3BRdTVwcWM... [undefined]
    at cfs_upload-http.js:351
    at cfs_upload-http.js:77
    at underscore.js:750
    at XMLHttpRequest.xhr.onreadystatechange (cfs_upload-http.js:200)PowerQueue.runTaskDone @ cfs_power-queue.js:494

**Comment by marryton007** [comment]
It seems access error server port, the meteor run at http://localhost:3000, not 8053. I have try another packager tool [meteor-electron](https://github.com/electron-webapps/meteor-electron#deploy) and that works fine.

**Comment by wojtkowiak** [comment]
Hey,

weird because it tries to upload the file to the default URL instead of server URL.
It think it is related to other problems collectionfs had on cordova. However since this package is deprecated I would suggest you to use https://github.com/VeliovGroup/Meteor-Files instead.
Also please note that `meteor-electron` does something very different than `meteor-desktop` - it displays your app from the web URL, not from a local webserver (the meteor app is not bundled).
Please let me know if your are fine with `meteor-electron` or should I investigate this issue?

**Comment by wojtkowiak** [comment]
Can this be closed?

**Comment by marryton007** [comment]
Thanks a lot, I have use Meteor-Files to instead of Meteor-CollectionFS, it works fine.

**Comment by marryton007** [comment]
Thanks a lot, I have use Meteor-Files to instead of Meteor-CollectionFS, it works fine.
