### ISSUE TITLE
meteor desktop system notifications

### ISSUE THREAD

**Issue by tzapu** [wojtkowiak/meteor-desktop#38]
Hi,

Made a module for enabling native system notifications in meteor desktop (thanks again) and wanted to see if you could take a look and maybe give us some pointers if there s something wrong, etc.

The plan is to extend this and make it a plugin, so any pointers in that direction are also most appreciated.

For now, it s simple and you can see the code here
https://gist.github.com/tzapu/14f92eb419c212768aa525112448261d

Thanks
Alex

**Comment by wojtkowiak** [comment]
Hey,

I am very excited for first plugin being made by somebody else than me 😄 
Just to let you know, I will respond to this in detail over the weekend. Probably tomorrow.

**Comment by wojtkowiak** [comment]
I just finally found a moment for this.
At first glance it looks fine. I have just run it.
Please make a repo for this plugin with a pull request - it will be easier for me to comment.

I am now thinking how to make such things simpler - I mean, you had to create a new window just to use `Notification` API - and that seems like an overkill. 

On the one hand, we can safely assume that Meteor app in Electron runs in Chrome, so you could skip creating a meteor-desktop plugin and just do that in a Meteor plugin, or just a npm package.
On the other hand there should be a possibility to load some code into the main window, so that it could expose api in the `Desktop` namespace saving you from creating a separate window just for that purpose.

I will probably add an API to load a file with code into the main file. For now you can start with this implementation.

**Comment by tzapu** [comment]
i completly agree with this 
**I mean, you had to create a new window just to use Notification API - and that seems like an overkill.**

looking forward to your changes. in the mean time we have it working properly as a module, will try to package it asap as a plugin and let you know.

thanks

**Comment by wojtkowiak** [comment]
Have you already made a repo for this plugin? I will start working soon on `0.4.0` where I am planning an API for directly adding code to renderer process - so just curious if you'd be still interested in this.

**Comment by tzapu** [comment]
hi, no repo yet, still at module level.
seems to be working find though

still interested in code for render process but it s not an urgent in any way, so maybe your time would be better spend on more pressing issues.

i ll try to make it a plugin asap, just worried that it will get a lot harder to debug...

thanks

**Comment by wojtkowiak** [comment]
>i ll try to make it a plugin asap, just worried that it will get a lot harder to debug...

Please check out the second paragraph https://github.com/wojtkowiak/meteor-desktop#how-to-write-plugins
With the use of `linkPackages` and having some tests it should not be a bad experience.

**Comment by wojtkowiak** [comment]
I can write the test if you want, as it requires some time to get accustomed to the test suite.

**Comment by tzapu** [comment]
thank you very much for all the help. i was under the impression linked packages wouldn't work, but now i know it should be a lot better

to my great shame, i must admit i m not very productive in test driven dev. never got into it properly, but i must really start. 

will throw a plugin together today/tomorrow and see your thoughts

thanks

**Comment by tzapu** [comment]
hi, 

the repo is here 
https://github.com/tzapu/meteor-desktop-system-notifications

it's also published and we re seeing now if it all works ok

long way to go as i want to add tests and all that jazz so any feedback is more than welcomed, including what your development flow is on plugins and so on

another thing that might be worth it if you would have a boiler plate plugin repo maybe
check it out and you would already have pretty much all the little files set to go, tweak a bit and drop your module...

**Comment by tzapu** [comment]
as the api/ipc commands for this are so simple, do you think it's worth having the meteor counterpart as well, just to abstract them?

**Comment by tzapu** [comment]
in our tests so far it seems to work fine which makes be very happy :D

we are getting this 
```
﻿﻿WARN  electronApp:  you are using outdated version 0.0.1 of meteor-desktop-system-notifications, the suggested version to use is undefined
```
not sure what else should of set

**Comment by wojtkowiak** [comment]
Sorry for no response from me. I was ill for some time. I will get back to this next week, ok?
Over the weekend I have a plan to release a fix for this erroneous warning.

**Comment by tzapu** [comment]
no worries man, you ve been a huge help anyway
thanks and get well soon

**Comment by michaelb-01** [comment]
Sorry for the stupid question...:

I'm trying to use this plugin, so i've installed it with:

`npm i meteor-desktop-system-notifications`

Then I added it to the plugins array in .desktop/settings.json so my plugins now looks like:

   ```
 "plugins": {
        "meteor-desktop-localstorage": "0.0.11",
        "meteor-desktop-system-notifications": {
            "version": "0.0.2"
        }
    },
```

However I don't quite know how to use the plugin, I tried this in 'main.ts' file in my server folder:

 ```
     Desktop.send('systemNotifications', 'notify', {
          title: 'Title',
          text: 'Text'
      });
```

I was getting a typescript error about 'Desktop' not being know so I added:

`let Desktop: any;`

But as expected this doesn't work and says can't read property 'send' of undefined. So I guess I actually need to import the module from somewhere. How do I do that?

**Comment by tzapu** [comment]
hi, i think you may need to wrap all that in Meteor.isDesktop

it should only be ran in a desktop app

hope this helps

**Comment by michaelb-01** [comment]
Hey thanks for your help but that gives me a typescript error:

`Property 'isDesktop' does not exist on type 'typeof Meteor'.`

And if I don't use the Meteor.isDesktop line my app crashes:

```
W20170306-21:09:24.194(0)? (STDERR) /Users/michaelbattcock/.meteor/packages/meteor-tool/.1.4.3_1.10pxpug++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170306-21:09:24.194(0)? (STDERR) 						throw(ex);
W20170306-21:09:24.195(0)? (STDERR) 						^
W20170306-21:09:24.195(0)? (STDERR) 
W20170306-21:09:24.196(0)? (STDERR) Error: Cannot find module './log'
W20170306-21:09:24.197(0)? (STDERR)     at require (packages/modules-runtime.js:123:19)
W20170306-21:09:24.198(0)? (STDERR)     at meteorInstall.node_modules.meteor-desktop.dist.desktop.js (packages/modules.js:1225:12)
W20170306-21:09:24.198(0)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
W20170306-21:09:24.199(0)? (STDERR)     at require (packages/modules-runtime.js:120:16)
W20170306-21:09:24.200(0)? (STDERR)     at meteorInstall.server.main.js (server/main.ts:24:15)
W20170306-21:09:24.200(0)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
W20170306-21:09:24.200(0)? (STDERR)     at require (packages/modules-runtime.js:120:16)
W20170306-21:09:24.201(0)? (STDERR)     at typings/site.ts:54:2
W20170306-21:09:24.201(0)? (STDERR)     at /Users/michaelbattcock/Documents/dev/apps/pipe/.meteor/local/build/programs/server/boot.js:303:34
W20170306-21:09:24.201(0)? (STDERR)     at Array.forEach (native)
```

Is there anything I need to add when using typescript? I'm importing the module with:

`import Desktop = require('meteor-desktop/dist/desktop.js');`

but i'm not sure if thats correct...

**Comment by sakujo** [comment]
@michaelb-01 did u solve ur problem? able to use isDekstop?
