### ISSUE TITLE
Can it work without online db?

### ISSUE THREAD

**Issue by nizulzaim** [wojtkowiak/meteor-desktop#39]
Hi, i know this is not issue, but it is support offline db without integrating with online server? I want to create offline application where it can create offline db. This is customer requirement. I dont like to create with windows application like vb and asp as i need lot of time to study back to that technology. If yes, how i can do that? As far as i understand, i need to have local server so that it can access local mongodb.

**Comment by wojtkowiak** [comment]
But you do have to have also the meteor server bundled, right? I mean mongodb alone will not benefit you in any way when using meteor client part.
If you want to bundle both meteor server and mongo - [electrify](https://github.com/arboleya/electrify) is what you want, there is a updated fork somewhere, you need to search for it.

This package will support it, I have this in plan, currently the ETA for bundling meteor server and mongo is middle of Q1 2017.

You can read more here: https://github.com/wojtkowiak/meteor-desktop/issues/19

**Comment by nizulzaim** [comment]
Yeah, while waiting your reply, i try search about possible solution. Then, i found out that you are not bundling mongodb with this package. Now, i need to try to make it work with electrify because my customer requirement is he want is offline app because the problem in network area coverage. Thanks.
