### ISSUE TITLE
dependencies not getting included in production build

### ISSUE THREAD

**Issue by tzapu** [wojtkowiak/meteor-desktop#41]
Hello,

We seem to have stumbled upon an issue when builds made for windows, on macOS, do not contain a dependency included in the module.
Tried to include the module in both settings.json or module.json
While building on macOS, the macOS build is ok, the windows build does not contain the dependency and errors. 
When building on windows the same thing, the win build contains the dependency.

Not sure at what to look next or what other details might be useful.
My module.json is 
```
{
    "name": "meteor-desktop-system-notifications",
    "dependencies": {
      "electron-notifications": "0.1.3"
    },
    "extract": []
}
```
Cheers

**Comment by wojtkowiak** [comment]
Hey,

are you 100% percent sure that the dependency is not there?
What is the exact error you are seeing?
Can you paste the `run.log`? On windows it is in `C:\Users\XXX\AppData\Roaming\YourAppName\run.log`

**Comment by smooth-operator** [comment]
Hello,

The error we get when we run a build generated on macOS on windows is:

2016-12-16T10:30:40.944Z - debug: [main] loading module: meteor-desktop-system-notifications => meteor-desktop-system-notifications
2016-12-16T10:30:40.958Z - error: [main] error while trying to load module in dir meteor-desktop-system-notifications: Error: Cannot find module 'electron-notifications'

The package is included in module.json as @tzapu mentioned above. When i build the same project on windows everything works fine.

Thanks

**Comment by tzapu** [comment]
for reference, here is the module.json
```
{
    "name": "meteor-desktop-system-notifications",
    "dependencies": {
      "electron-notifications": "0.1.4"
    },
    "extract": []
}
```

**Comment by tzapu** [comment]
also, when i build on os x for os x, everything is fine.
the only builds that are having that issue are cross builds on os x for win

thanks

**Comment by wojtkowiak** [comment]
I think I know what is going on here. I will need to resolve it together with the author of `electron-builder` so it can take a few days before we will bot release new versions. If you need that fix sooner let me know and I will think about some possible workarounds.

**Comment by tzapu** [comment]
hi, thanks for looking into this.

there is no rush, as we can each make builds for our respective systems.

cheers

**Comment by wojtkowiak** [comment]
`0.3.0` was released today. This should be now working as it should. I would appreciate if you could find a moment to test it.

**Comment by tzapu** [comment]
hi, gave it a try and i get the following
```
ERROR  electronBuilder:  error while building installer:  Error: Since electron-builder 11, module electron-builder-squirrel-windows must be installed in addition to build Squirrel.Windows: Error: Cannot find module 'electron-builder-squirrel-windows'
```
not sure where to add the dep though

also, i ve noticed this which doesn't seem ok
```
WARN  electronApp:  you are using outdated version 0.1.0 of meteor-desktop-splash-screen, the suggested version to use is 0.0.31
```

hope this helps and thank you

**Comment by tzapu** [comment]
i was able to get it building by `npm install electron-builder-squirrel-windows`. maybe this should be in dependencies instead of devDependencies?

testing the rest now

**Comment by wojtkowiak** [comment]
> i was able to get it building by npm install electron-builder-squirrel-windows. maybe this should be in dependencies instead of devDependencies

Yes, fix is on the way 👍

**Comment by wojtkowiak** [comment]
> WARN  electronApp:  you are using outdated version 0.1.0 of meteor-desktop-splash-screen, the suggested version to use is 0.0.31
Thanks for noticing, will be fixed.

**Comment by tzapu** [comment]
@wojtkowiak great job man, it works nicely

built on os x both 64 and 32 bit and was able to run on windows and module was loaded

thanks for all your efforts
