### ISSUE TITLE
[Question] How to use External Mongodb?

### ISSUE THREAD

**Issue by cezerii** [wojtkowiak/meteor-desktop#43]
Hi, 
is it possible to use external mongodb?

**Comment by wojtkowiak** [comment]
Hey,
what do you mean by external?
This integration does not bundle Meteor server nor MongoDB, it is only a client.
So in the place where you have your meteor server deployed you can normally use any MongoDB instance.

**Comment by cezerii** [comment]
Mongodb not working in meteor in my project. Both of them are on same computer. Mongodb always works on 27017 port as a service.

**Comment by wojtkowiak** [comment]
This is still unclear to me.
What this problem is related to - Meteor or `meteor-desktop`?
I mean, you have a problem because the client generated by `meteor-desktop` cannot connect through DDP to your meteor server or your meteor server cannot connect to the database?

**Comment by cezerii** [comment]
i got it .thank you

**Comment by wojtkowiak** [comment]
Can this be closed? I am also curious what was the problem you were experiencing. Was that related to `meteor-desktop`?

**Comment by wojtkowiak** [comment]
No problem 🙂  So closing this task.
