### ISSUE TITLE
Modules not working on Windows?

### ISSUE THREAD

**Issue by dnish** [wojtkowiak/meteor-desktop#44]
Hey, 
just had the chance to test our production app on a Windows device. I've just noticed that none of our modules was loaded (f.e. window resize, music control buttons, download). The app was built on Mac and the Mac version works fine without any problems. Any idea what went wrong?

**Comment by dnish** [comment]
It's like my issue #25 but only on Windows.

**Comment by wojtkowiak** [comment]
Are those modules dependent on any npm packages? There are some issues currently when doing a build for platforms different that the platform you are running meteor-desktop on. I am working with the owner of electron-builder to solve them. Should be more reliable in `0.3.0`.
And as usual, can you post the run.log?

**Comment by dnish** [comment]
Yeah, I'm using <code>electron-dl</code> which has been added through npm. I'll have access to a Windows device next week again so I can post the run.log here.

**Comment by dnish** [comment]
@wojtkowiak Just build our app with Windows, can approve that this solved the issue.

**Comment by wojtkowiak** [comment]
This should be now working properly in `0.3.0`.
