### ISSUE TITLE
meteor-desktop vs meteor-electron

### ISSUE THREAD

**Issue by jdnichollsc** [wojtkowiak/meteor-desktop#47]
Hi guys!

Thanks for this project! One question, what's the difference between **meteor-desktop** and **[meteor-electron](https://github.com/electron-webapps/meteor-electron)**?

Thanks in advance, Nicholls

**Comment by wojtkowiak** [comment]
Hey,

sorry for late answer. 
It is hard to answer actually. `meteor-electron` is rather simple integration that just displays your app from the url. So it will not work offline. You are basically just writing an Electron app that displays your meteor app's from the url. Basic packaging and electron auto-update support is also in place. It does not provide much more than that afaik.  Also it seems that `meteor-electron` is not maintained anymore.
`meteor-desktop` is much more richer in features and it makes a full desktop client meaning the meteor app is bundled and a full hot code push mechanism is implemented (just like in mobile builds) so the app can work offline. 

I will add a short comparison between the available integrations to readme soon.

**Comment by jdnichollsc** [comment]
Excellent, thanks Sir for the explanation and this project! Is amazing!
Regards, Nicholls
