### ISSUE TITLE
Changing webPreferences in settings.json causes the preload.js file to get lost

### ISSUE THREAD

**Issue by calebl** [wojtkowiak/meteor-desktop#48]
Under "window" in the settings.json file, if I set anything in "webPreferences" then I get a console error when I run Electron that says Desktop is not defined. The only thing I can figure is that this portion of the settings is overwriting the windowSettings object created in app.js on line 445 specifying the location of the preload.js file.

**Comment by wojtkowiak** [comment]
Hey, thanks for this report.
Yes that is indeed the cause. If you are overwritting `webPreferences` the url for the preload file will be lost unless you set it yourself.
https://github.com/wojtkowiak/meteor-desktop/blob/master/skeleton/app.js#L450
I will add a check that will restore the `preload` in case `webPreferences` are set in settings.
This will be fixed tomorrow with `0.3.0` release.

**Comment by calebl** [comment]
Awesome! Thanks for you work on this.

**Comment by wojtkowiak** [comment]
`0.3.0` is now released. Please let me know if that helps.

**Comment by calebl** [comment]
That seems to have fixed it!
