### ISSUE TITLE
Add reason when Desktop.fetch rejects with timeout

### ISSUE THREAD

**Issue by calebl** [wojtkowiak/meteor-desktop#54]
Currently reject() is called (line 210 of preload.js) without a reason given which logs as a Promise rejected for an undefined reason. Took me awhile to figure out that my fetches were timing out.

**Comment by wojtkowiak** [comment]
Can it just reject to `timeout` string or would you like to specify the value of timeout rejection?

**Comment by calebl** [comment]
Just timeout makes sense to me. Or maybe the name of the module and the event and timeout.

**Comment by wojtkowiak** [comment]
Forgot to notice you. This is in place for some time now
https://github.com/wojtkowiak/meteor-desktop/blob/master/skeleton/preload.js#L210
