### ISSUE TITLE
Cannot use window.setMenu()

### ISSUE THREAD

**Issue by justinglibert** [wojtkowiak/meteor-desktop#62]
I didn't find a way to use windows.setMenu() (I want to remove all the menu items)
Is it possible to expose the window object in desktop.js ?

**Comment by wojtkowiak** [comment]
Yes, the `window` object is received through an event.

https://github.com/wojtkowiak/meteor-desktop/blob/master/scaffold/desktop.js#L44

**Comment by wojtkowiak** [comment]
Did you manage to do that or do you need more help?

**Comment by justinglibert** [comment]
No thank you, it's a perfect solution !!

**Comment by wojtkowiak** [comment]
So closing 👍
