### ISSUE TITLE
Way to check if native update is needed?

### ISSUE THREAD

**Issue by dnish** [wojtkowiak/meteor-desktop#65]
Hey @wojtkowiak,
is it possible to check within a Meteor application if an native update is required (f.e. switching from 0.4 to 0.5). We want to show our users that they need to download a new release to have the newest version of our app.

**Comment by ethanwillis** [comment]
@dnish I think you can do this using the built in squirrel update mechanism. Essentially you would.

1.) In your development environment you would update your versions. 
2.) Then build new installers. 
3.) Then you upload those new installers to your [electron-release-server] instance. (https://github.com/ArekSredzki/electron-release-server)

In step 1 you would need to..
Modify your client code within your app to check for updates. You do this by calling to the autoupdate module within meteor-desktop like so: 
```
Desktop.send("autoupdate", "checkForUpdates");
```
See my issue: #66 

For more info on the autoupdate module in meteor-desktop see this file https://github.com/wojtkowiak/meteor-desktop/blob/07d7a005e5a6b47c14addca4cbe3d55723cb7ff9/skeleton/modules/autoupdate.js#L77
