### ISSUE TITLE
Question on building for production

### ISSUE THREAD

**Issue by Ajaay** [wojtkowiak/meteor-desktop#68]
Hi,

I think I'm missing something obvious, but if I want to build for production do I simply specify my apps host:port in the --mobile-server command? i.e.

```meteor --mobile-server=<prod hostname>:<prod port> --settings settings-production.json```

Then build the installer..

```npm run desktop -- build-installer --production```

When I do this and run the app, I don't see any established connections on my machine to my production host, and I can't login to my app as you would expect.

Any ideas?

Thanks!

**Comment by wojtkowiak** [comment]
Hey,
this seems strange. Basically, if you use the `-b` option like `npm run desktop -- build-installer -b` the ddp url will be set to `http://127.0.0.1:3000`.
If you do not use `-b` the url passed to `--mobile-server` should be preserved.
Does it work when you just use `npm run desktop` or `npm run desktop -- --production`?

**Comment by Ajaay** [comment]
Ok so if I just do npm run desktop (whilst the app is running locally with mobile-server pointed at prod app) I get the following error in the console:

XMLHttpRequest cannot load http://<host hidden>:443/sockjs/info?cb=4jo_ris_gs. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:8037' is therefore not allowed access.

**Comment by Ajaay** [comment]
After a little reading of Meteor's Cordova docs I tried adding the following to a Meteor.startup() function:

```// Listen to incoming HTTP requests, can only be used on the server
	WebApp.rawConnectHandlers.use(function(req, res, next) {
  		res.setHeader("Access-Control-Allow-Origin", "*");
  		return next();
	});```

But no joy unfortunately :(

**Comment by wojtkowiak** [comment]
Weird, because I have never encountered that and I have two apps on production.
Do you have `App.accessRule("*");` in `mobile-config.js` ? I just took a look there and that is the only thing I have set there. I do not have time now to check if it fails without it.

**Comment by Ajaay** [comment]
Are either of those working apps deployed to Galaxy?

I will look into the accessRule now

**Comment by wojtkowiak** [comment]
Nope, I have a custom made docker based production env. App container is proxied through ngnix but that should not matter.

**Comment by Ajaay** [comment]
Ok I didn't have a mobile-config.js file, so I've added that and included the accessRule but that hasn't sorted it...

What do you think about this as a potential candidate?

https://guide.meteor.com/mobile.html#configuring-server-for-hot-code-push

Thanks!

**Comment by Ajaay** [comment]
Managed to fix it :)

Had to specify https in the mobile server command. So:

--mobile-server=https://<host>:443

Probably don't need the 443 on the end but haven't tested without it.

Might be something good to add as an FYI in the docs for other people using Galaxy? 

Cheers

**Comment by wojtkowiak** [comment]
Oh I did not notice the lack of `s` in `http`. Thanks for the info 👍 
Glad that you've sorted it out.
