### ISSUE TITLE
Meteor.userId()

### ISSUE THREAD

**Issue by michaelb-01** [wojtkowiak/meteor-desktop#72]
I'm using Meteor.userId() to check if the user is logged in (so I can choose whether or not to display data) however this doesn't seem to be working with meteor-desktop. Is there an alternative or suggested workaround?

**Comment by wojtkowiak** [comment]
Hey,
well, it should work, and works normally 🙂 
I have two production apps now and never had problems with this. That of course does not mean you did not hit a case where it doesn't work.
Can you be more specific? Can you paste the code from client and server where this occurs?

**Comment by KoenLav** [comment]
@wojtkowiak suggest to close this issue due to inactivity.
