### ISSUE TITLE
missing script: desktop

### ISSUE THREAD

**Issue by nosizejosh** [wojtkowiak/meteor-desktop#74]
Hello, Please help. 
I have followed all instructions successfully, except the last part

> npm run desktop --init 

produces the error below

> J:\xampp\htdocs\ns\17\Desktop Apps\Meteor\todos>npm run desktop -- init
> npm ERR! Windows_NT 10.0.14393
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "desktop" "--" "init"
> npm ERR! node v4.4.7
> npm ERR! npm  v2.15.8
> 
> npm ERR! missing script: desktop
> npm ERR!
> npm ERR! If you need help, you may report this error at:
> npm ERR!     <https://github.com/npm/npm/issues>
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     J:\xampp\htdocs\ns\17\Desktop Apps\Meteor\todos\npm-debug.log
> 
> J:\xampp\htdocs\ns\17\Desktop Apps\Meteor\todos>npm run desktop
> npm ERR! Windows_NT 10.0.14393
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "desktop"
> npm ERR! node v4.4.7
> npm ERR! npm  v2.15.8
> 
> npm ERR! missing script: desktop
> npm ERR!
> npm ERR! If you need help, you may report this error at:
> npm ERR!     <https://github.com/npm/npm/issues>

**Comment by gooor** [comment]
space before init
`npm run desktop -- init`

**Comment by nosizejosh** [comment]
@gooor thank you so much.
