### ISSUE TITLE
Attempting to acces Node net module in client.js

### ISSUE THREAD

**Issue by KoenLav** [wojtkowiak/meteor-desktop#75]
I'm attempting to access the Net module in client code.

Accessing the OS module works just fine (const os = require('os')), but accessing the net module seems more difficult (const net = require('net') returns undefined).

Any pointers would be greatly appreciated!

**Comment by KoenLav** [comment]
When I import net (import net from 'net') in .desktop/modules/example/index.js it is working fine though, so I'm going to try to pass it from there into the client/access it there.

Pointers still appreciated!

**Comment by KoenLav** [comment]
Ok, so I figured out I can use Desktop.sendGlobal(Desktop.getEventName('example', 'testEvent')) to trigger the event in the module,

**Comment by wojtkowiak** [comment]
Hey, glad you have figured it out.
Sorry for no help from me.  Usually I respond faster but this week is hectic for me 🙂 
Best regards

**Comment by KoenLav** [comment]
Hi wojtkowiak, not a problem at all!

I simply figured why re-invent the wheel, but I managed to find out without investing too much time :)

Now I'm trying to figure out how to make the app launch fullscreen and remove the File, Edit, etc. buttons (kiosk mode) ;)

**Comment by wojtkowiak** [comment]
> Now I'm trying to figure out how to make the app launch fullscreen and remove the File, Edit, etc. buttons (kiosk mode) ;)

In settings have sth like:
```
    "window": {
        "fullscreen": true,
        "kiosk": true,
        "alwaysOnTop": true,
```

> and remove the File, Edit, etc. buttons

Those are removed automatically in the build (they are added by Electron runing in dev mode). You can check it by packaging or building installer: `npm run desktop -- package` or `npm run desktop -- build-installer` - they should not be present in the packaged version.

**Comment by KoenLav** [comment]
I found those options indeed, but when I press F11 to resize the window back from kiosk/fullscreen it renders an all-black window on Windows 10 (with which I can't interact anymore).

Any ideas?

I'm diving into the Electron docs/issues to see whether I can find a fix, but should you have prior experience with this issue, do tell ;)

**Comment by KoenLav** [comment]
https://github.com/electron/electron/issues/6036

**Comment by KoenLav** [comment]
I'll take it up there :)
