### ISSUE TITLE
How can I change the default starting URI and dynamically set the server?

### ISSUE THREAD

**Issue by sputnick** [wojtkowiak/meteor-desktop#78]
Thanks for a great library! I'm trying to figure out how to change the default URI from "/" to something else like "/compute" and ALSO more importantly how can I build the app so that I can change the server URL on startup? 

The reason why the server URL needs to be dynamic is that the webapp can deployed on many servers by different people so the DNS name or IP address and port will change even though the code stays the same. In other words the meteor app will be deployed in a docker container and I need to figure out what the end server URL (ip, port and uri) is on startup or after startup and feed that to meteor-desktop...

**Comment by sputnick** [comment]
My plan btw is also to have the meteor-desktop app deploy the container by calling some script or code. Where would a hook for that be in the code?

**Comment by wojtkowiak** [comment]
Hey @sputnick,
first we need to clarify some terms because I am not sure at the moment what you are actually trying to achieve 🙂 
> URI from "/" to something else like "/compute"

What do you mean by URI? Do you mean the DDP url - the address of meteor server to which the client connects to? If yes then you can just pass it as the first argument to any command of meteor-desktop like `npm run desktop -- http://any.url/sth'

> In other words the meteor app will be deployed in a docker container and I need to figure out what the end server URL (ip, port and uri) is on startup or after startup and feed that to meteor-desktop...

At the moment I do not see any possibility to do that. Do you care about having hot code push? If not then you can simply use `DDP.connect` from meteor itself, as meteor allows you to have additional DDP connection and it does not care if the default one does not work, so you can point your app to a dummy url and connect to the right one with DDP.connect. You just need to pass the connection instance to your collections.
If using DDP.connect is not an option for you than I can think of a change that would allow you to do that but you will have to wait for it from 2 to 4 weeks.

> My plan btw is also to have the meteor-desktop app deploy the container by calling some script or code. Where would a hook for that be in the code?

Not sure also what do you mean. You just want to execute something from meteor-desktop? If yes than you do it through normal node child process api. Just wrap it into a [IPC event](https://github.com/wojtkowiak/meteor-desktop#module---desktop-side) on the desktop side and call it with `Desktop.send('module', 'event');`

**Comment by sputnick** [comment]
hey @wojtkowiak thanks for the quick reply.

I'm a bit confused by it but let's try and work it out ;)

I've managed to build an app with meteor-desktop that connects to a local meteor app and found a way to get past the app starting point problem (the URI) from the meteor side (I changed the route to "/" from "/compute" for the part of the app that I want in meteor-desktop).

The meteor server URL seems is hard coded in the skeletonApp.js with no way of augmenting it.
https://github.com/wojtkowiak/meteor-desktop/blob/master/skeleton/app.js#L523

I think it would be a nice feature to be able to edit the url before it is used from a module e.g. from a listener of "windowCreated" or "beforeURL" but neither of those can affect or change the URL.

What I don't quite understand in your reply is why I would be running "npm desktop serverURL" as an end user? I use that now for testing the meteor-desktop app and I'm starting to develop custom desktop app features using a module and standard Electron stuff (nice module system!). However I want to make my installer a downloadable and when users start the app I will ask them (using Electron UI components) which server (same meteor app but running in different locations) they want to connect to. That's the dynamic URL I'm referring to.

Maybe I'm misunderstanding how this works. I haven't seen one complete example app yet so I'm filling in the blanks by trial and error...

cheers
Eiki

**Comment by sputnick** [comment]
Maybe you can answer these questions to give me some clarity.

Is meteor-desktop running a local server that is essentially a copy of just the client part of the meteor app it is built on? If so then I understand why the IP address is always 127.0.0.1 and the port randomized. I thought that URL in the skeletonApp was the URL for the remote meteor server.

Is the URL in the skeletonApp for the default app chrome window or is it the DDP url for the client code?

**Comment by wojtkowiak** [comment]
Sorry for the break in communication. I will try to catch up with this today/tomorrow.

**Comment by sputnick** [comment]
Thanks

**Comment by wojtkowiak** [comment]
> Is meteor-desktop running a local server that is essentially a copy of just the client part of the meteor app it is built on? If so then I understand why the IP address is always 127.0.0.1 and the port randomized. I thought that URL in the skeletonApp was the URL for the remote meteor server with the URI part of the app too.

Yes, meteor-desktop is running only your client on a simple customized http server (it is mimicking a normal situation when you load your app from url in a browser, just like cordova integration does). 

> Is the URL in the skeletonApp for the default app chrome window or is it the DDP url for the client code?

This is not the DDP url (address of your meteor server).
When building a mobile app you can pass a `--mobile-server=<ddp_url>` to meteor, and that is the address of the server it will connect to. The same applies here. You can pass an address `npm run desktop -- <ddp_url>`.

> However I want to make my installer a downloadable and when users start the app I will ask them (using Electron UI components) which server (same meteor app but running in different locations) they want to connect to.

That is currently very hard in meteor itself. Imagine you have your meteor server deployed at url1 url2 and url3. If you want to type url1 in the browser and make the loaded app to connect to url2 it is impossible unless you will do some hacking.

I have an mobile app where you can do exactly what you are asking for. And the way I did that is the default ddp_url only points the app to the instance that serves hot code pushes. User selects the server and from that point I am connecting through [DDP.connect](http://docs.meteor.com/api/connections.html#DDP-connect). You can then have collections and publications subscribed from that server. You can also login with AccountClient: http://docs.meteor.com/api/accounts-multi.html. So it is a little harder but doable.

**Comment by wojtkowiak** [comment]
Can this be closed?
