### ISSUE TITLE
desktopHCP breaks appHCP and cordovaHCP

### ISSUE THREAD

**Issue by KoenLav** [wojtkowiak/meteor-desktop#87]
desktopHCP support is experimental, I am aware.

I expected it not to work, but it also broke HCP of the app code (in the desktop as well as cordova version).

Just a head's up!

**Comment by wojtkowiak** [comment]
By appHCP you mean the reload in browser?

Could you provide more details? Scenario, logs etc?

We are using desktopHCP normally when developing and also on production for one the products and so far we did not experience any major problems so far.

**Comment by KoenLav** [comment]
What I noticed is that when I enabled desktop HCP, the HCP in the app
(Android/iOS) stopped working.

Also desktop HCP didn't seem to be working at all (even in development).

Op 18 apr. 2017 9:26 a.m. schreef "Bartosz Wojtkowiak" <
notifications@github.com>:

**Comment by wojtkowiak** [comment]
That is very interesting. I would like to debug it further if you have time 🙂 

Do you have those plugins added: ?
```
omega:meteor-desktop-watcher@=0.6.2
omega:meteor-desktop-bundler@=0.6.2
```

Do you see anything in the console of the mobile apps in regard to HCP?
Do you see anything in the console of the desktop app in regard to HCP?
Does the HCP is normally applied in the browser (you see the restart of the app)?
Do you get any errors in the console?

**Comment by KoenLav** [comment]
omega:meteor-desktop-watcher@=0.6.2
omega:meteor-desktop-bundler@=0.6.2

Are added.

HCP of Meteor code changes would work during development.

HCP of Desktop changes would not work during development.

HCP of Meteor nor Desktop code would work in production.

For now I have disabled desktopHCP, as it is not a requirement for our use-case, but I will dive further into it (probably in May).

`{
    "name": "MrWinston",
    "version": "2.1.5",
    "projectName": "MrWinston",
    "devTools": true,
    "devtron": true,
    "desktopHCP": true,
    "desktopHCPIgnoreCompatibilityVersion": false,
    "autoUpdateFeedUrl": "http://127.0.0.1/update/:platform/:version",
    "autoUpdateFeedHeaders": {},
    "autoUpdateCheckOnStart": true,
    "rebuildNativeNodeModules": false,
    "webAppStartupTimeout": 60000,
    "exposeLocalFilesystem": false,
    "experimentalLocalStorage": true,
    "window": {
        "icon": "@assets/meteor.png",
        "_windows": {
            "icon": "@assets/meteor.ico"
        },
        "frame": true
    },
    "windowDev": {
    },
    "uglify": true,
    "plugins": {
        "meteor-desktop-splash-screen": {
            "version": "0.3.0",
            "windowSettings": {
                "width": 800,
                "height": 600
            }
        }
    },
    "dependencies": {},
    "packageJsonFields": {
        "description": "MrWinston",
        "author": "MrWinston",
        "private": true
    },
    "builderOptions": {
        "win": {
            "title": "MrWinston",
            "authors": "MrWinston",
            "target": "nsis"
        },
        "squirrelWindows": {
            "iconUrl": "https://github.com/wojtkowiak/meteor-desktop/blob/beta/scaffold/assets/meteor.ico?raw=true",
            "loadingGif": ".desktop/assets/loading.gif"
        },
        "icon": ".desktop/assets/meteor.ico",
        "appId": "mrwinston.app",
        "productName": "MrWinston",
        "compression": "maximum",
        "mac": {
            "icon": ".desktop/assets/meteor.icns"
        },
        "dmg": {
            "icon": ".desktop/assets/meteor.icns",
            "background": ".desktop/assets/dmgBackground.png",
            "iconSize": 54,
            "contents": [
                { "x": 377, "y": 190, "type": "link", "path": "/Applications" },
                { "x": 63, "y": 190, "type": "file" }
            ],
            "window": {
                "width": 480,
                "height": 300
            }
        }    },
    "packagerOptions": {
        "icon": ".desktop/assets/meteor.ico",
        "_osx": {
            "icon": ".desktop/assets/meteor.icns"
        },
        "version-string": {
            "CompanyName": "MrWinston",
            "LegalCopyright": "Copyright",
            "FileDescription": "MrWinston",
            "OriginalFilename": "MrWinston.exe",
            "FileVersion": "@version",
            "ProductVersion": "@version",
            "ProductName": "MrWinston",
            "InternalName": "MrWinston.exe"
        }
    }
}
`

**Comment by KoenLav** [comment]
Have been looking into this today.

Might this problem be related to: if your run a production build of your desktop app it will not receive updates from project run from meteor command unless you run it with --production - that is because development build has devtron added and therefore the compatibilityVersion is different.

We use meteor-up (zodern/meteor-up) to deploy, not sure whether this makes use of the --production flag by default...
