### ISSUE TITLE
localStorage doesn't work in production, but does in development

### ISSUE THREAD

**Issue by KoenLav** [wojtkowiak/meteor-desktop#88]
At Meteor.startup we fetch some clientSettings which are stored in localStorage. While developing localStorage seems to be in place before the chrome window is even rendered, but in production it seems the localStorage plugin doesn't work/load quickly enough.

I'm not sure why localStorage is not working in production, but I thought it might be caused by a race condition. I then tried to listen to the localStorage.loaded event, but couldn't get that to work.

Any pointers?

**Comment by KoenLav** [comment]
Apologies, didn't catch this one:

https://github.com/wojtkowiak/meteor-desktop/issues/63

Will try with the new experimentalLocalStorage

**Comment by sferoze** [comment]
@KoenLav 

did the experimentalLocalStorage key work for you?

for me it is not doing anything? Everytime I open the app it creates new localstorage.

**Comment by KoenLav** [comment]
Yeah, it's working fine for us!

Code sample:

`      const instanceSettings = {
        name: 'clientSettings',
        version: 2
      }

      if (Meteor.isDesktop) {
        instanceSettings.driver = localforage.LOCALSTORAGE
      }

      ClientSettings.store = localforage.createInstance(instanceSettings)`

**Comment by sferoze** [comment]
@KoenLav ah cool! I actually came up with the same solution last night! 

The only thing I am wondering is the use of `version: 2` 

Ground:db uses `version: 1` by default. Any reason you have `version: 2`?

**Comment by KoenLav** [comment]
Great! 

Yeah, we had a previous version of our application in which we used Ground DB, now we are no longer using it. 

Hence I upped the storage version to 2 (to avoid interactions between the old, grounded, data and our new structure). 

Just out of interests; what are you using ground db for?

**Comment by sferoze** [comment]
ah cool. I am using ground db to save a subset of the users data. So they can open the app offline. So I ground the user document as well as a bunch of other info needed for basic functionality. 

With the grounded data, and meteor-desktop, a user can now open the app completely offline, make edits, updates etc. and then next time they have a connection the app will sync the data. 

I also tried upping the version to 2 in ground:db and it seems to work like normal. So I am just gonna roll with it.

**Comment by KoenLav** [comment]
@sferoze nice!

We implemented something similar, but ended up removing it because sometimes the data would end up being corrupted  (we have also Tenantified our application, sometimes the data from a previously logged in tenant would still be available).

Would you care to share your implementation, maybe we could give that one a try ;) (I would understand if not, totally fine.)

**Comment by KoenLav** [comment]
I've yet to experience any bugs with the experimental localStorage version.

For people experiencing similar problems, add:

    "experimentalLocalStorage": true,

to your settings.json in .desktop.

**Comment by gmacherey** [comment]
Hello all, I am struggling with the same things, trying to use ground:db with meteor-desktop.

Could you explain how to implement ? Would be really, greatly appreciated :)

Thanks a lot !
