### ISSUE TITLE
Question about Cordova and mobile platform dependency

### ISSUE THREAD

**Issue by btbjosh** [wojtkowiak/meteor-desktop#89]
This may be a dumb question, so I apologize in advance. But why do I need to have a mobile platform installed in order to make a "thin client" electron desktop build of my app?

I see this: 
`*2 you can always build with --server-only if you do not want to have mobile clients, you do not actually have to have android sdk or xcode to go on with your project` 
but I am not familiar with this and research into the Meteor docs indicate that it's strictly for making a build... Which leads me to my next question... I normally use Mup to deploy so I don't operate within the standard build process that meteor employs (except that it's handled for me)... So if I don't want to have any mobile clients or utilize cordova, can I just make a build and then use the `run desktop <ddp url>` somehow?

I see that the first paragraph in the instructions talk about how it takes the cordova build from the `.meteor` folder... but the prior caveat makes it sound like there's a way around this.

If anyone could shed some light, I would be very appreciative. :)
Thanks!

**Comment by sputnick** [comment]
I had the same question when I first saw the project and never got the --server-only to work. I think the mobile part is just so a platform specific binary can be built and you are not bundling nodejs code in the final app. It works on OSX.

**Comment by sputnick** [comment]
@btbjosh This is what I did to get it working for me on OSX. I needed two scripts. First one adds the npm packages and mobile capabilities to the meteor project + runs the server and the second one actually builds the app. Hope this helps.

**Build script 1 from a /build folder in my project**
```
#!/bin/bash
cd ../themetorappfolder
#make sure meteor is up to date
meteor reset
meteor npm prune
meteor add-platform ios
meteor npm install
meteor npm install --save-dev meteor-desktop

meteor --mobile-server=127.0.0.1:3000 --settings mycustommeteorsettings.json
echo 'NOW OPEN A NEW TERMINAL AND RUN BUILD STEP 2'
```


**Build script 2 from same /build folder**
```
#!/bin/bash
#this creates the .desktop folder and runs the app
cd ../themetorappfolder
#this step is just for when you have copied and customized the assets
#cp ../assets/* .desktop/assets/

#npm run desktop -- --scaffold
#npm run desktop build
npm run desktop build-installer

#on OSX the build puts the app/installer under themetorappfolder/.desktop-installer/mac/
#open in Finder
open .desktop-installer/mac/
echo 'Done building the app'
```

**Comment by btbjosh** [comment]
@sputnick Thanks. I actually was missing a step with the mobile server pointing to my wrong settings file (i have a few of them for different environments)... So that helped. I got it working now :) Pretty slick.

Thanks again!

**Comment by wojtkowiak** [comment]
FYI: in `0.7.0` you can now pass `--meteor-settings` to pass settings.json. This only works with `-b` so when `meteor-desktop` is building the meteor project for you.
