### ISSUE TITLE
Single-line-log output makes tracing build errors very difficult or impossible

### ISSUE THREAD

**Issue by angryrancor** [wojtkowiak/meteor-desktop#94]
Hi again :) 🥇 

Using the 'build-installer' command, I have noticed that single-line-log is being used in many cases for build outputs.  This has the effect of multi-line build output messages/failures being almost completely hidden.

I understand the use of single-line-log for simple progress bars and counters, as is its intended use, however the build output with build-installer not a progress bar or counter.

For the time being we have just forked single-line-log and taken out the clear / truncation of output, however a better solution would be to route the build-installer command to a non-SLL stream.  If I have some time I may fork and attempt that myself, any assistance would be appreciated :) :)

**Comment by wojtkowiak** [comment]
Hey @angryrancor,
just to make it clear you mean the part when the meteor build is being done (`-b` option) or the part when `electron-builder` is preparing the installer?

**Comment by angryrancor** [comment]
Specifically electron-builder preparing the installer.

**Comment by wojtkowiak** [comment]
Cleaning up the backlog 🙂 More logs from electron-builder can be achieved using `DEBUG=electron-builder`.
Let me know if this can be closed?
