### ISSUE TITLE
Using MDG Camera package in Electron Desktop

### ISSUE THREAD

**Issue by sferoze** [wojtkowiak/meteor-desktop#97]
Hi,

I am using MDG Camera package which allows you to take a picture on any device you are on. 

But this package is not included in the desktop build. Below is the package.js 

The lines below show that the css and js is added to `web.browser`. 

```
api.addFiles("camera.less", ["web.browser"]);
api.addFiles('photo-browser.js', ['web.browser']);
```

But we need these added to the desktop as well. But the exported variable `MeteorCamera` exported by `api.export('MeteorCamera');` is not defined. 

Below is the whole package.js for mdg:camera. Let me know how I can have this added to the desktop build. 

```javascript
Package.describe({
  name: "mdg:camera",
  summary: "Photos with one function call on desktop and mobile.",
  version: "1.4.1",
  git: "https://github.com/meteor/mobile-packages"
});

Cordova.depends({
  "cordova-plugin-camera": "2.3.1"
});

Package.onUse(function(api) {
  api.export('MeteorCamera');
  api.use(["templating", "session", "ui", "blaze", "less@1.0.0||2.0.0", "reactive-var"]);
  api.versionsFrom("METEOR@1.2");
  api.use("isobuild:cordova@5.2.0");

  api.addFiles('photo.html');
  api.addFiles('photo.js');
  api.addFiles("camera.less", ["web.browser"]);
  api.addFiles('photo-browser.js', ['web.browser']);
  api.addFiles('photo-cordova.js', ['web.cordova']);
});
```

UPDATE:

Actually MeteorCamera is defined but the package fails because `navigator.camera.getPicture ` is not defined which MeteorCamera uses.

**Comment by sferoze** [comment]
UPDATE:

Ohh, actually, what is happening is that the MDG:Camera package is trying to use the cordova method for getting a picture instead of the browser method, since we are grabbing the cordova build. 

Ah so basically we need to add api.addFiles('photo-browser.js', ['web.browser']); to the desktop platform

**Comment by wojtkowiak** [comment]
Yes, you are right. Its including the cordova files. This is unfortunately a drawback when it comes to the way meteor-desktop is implemented and without hacking there is not much I can do about it.
I do not like it when I need to suggest a workaround but in this case you will have to make a fork of that package and do some changes.
If you do not need it working on cordova just change `web.browser` to `client` in package.js
If you do need cordova,  then do the same as above but remove photo-cordova.js and add its contents to photo-browser wrapping the definition of `MeteorCamera.getPicture` into an if. 

```javascript
if (!Meteor.isCordova) {
 MeteorCamera.getPicture // from photo-browser.js
} else {
 MeteorCamera.getPicture // from photo-cordova.js
}
```

**Comment by wojtkowiak** [comment]
Have you manage to work it out?

**Comment by sferoze** [comment]
Oh yah was easy, just had to extract the photo-browser.js code and use that on the desktop side.
