### ISSUE TITLE
Document.domain is 127.0.0.1 instead of using the DDP url domain

### ISSUE THREAD

**Issue by sferoze** [wojtkowiak/meteor-desktop#98]
I noticed that in the console if you type `document.domain` it prints `127.0.0.1` in the desktop app.

But in the browser `document.domain` shows the DDP url. 

Is this going to cause any issues, or is this correct? I don't notice any real issues, the only thing that brought it to my attention is when an iframe shows itself, sometimes it complains about document.domain. But I am not sure how to reproduce this error reliably, or even why it occurs. Just thought I would bring up this issue in case it is something important to fix. 

If not feel free to just close this issue.

**Comment by wojtkowiak** [comment]
In desktop app, your meteor app is served from a local web server so you will always have `127.0.0.1` (the same applies for cordova). In the browser you will have the url from your meteor server which is always the same as your ddp_url. Well the second part is not always true, but in 99% cases it is. You can allways type `__meteor_runtime_config__` in the console to verify if everything is as it should.

> when an iframe shows itself, sometimes it complains about document.domain

I would be very interested in getting to know what that error exactly is. The first thing I can think of is that you can probably get some CORS issues if you are using the iframe to get something from the outside of localhost. What are using the iframe for?

**Comment by wojtkowiak** [comment]
And BTW thanks for reporting the issues 👍
